/**
 * Explicit machine-readable permission codes (section 6). Business modules
 * added in later phases append their own `<module>.<resource>.<action>`
 * codes here/in their own module — never hardcode role names in logic.
 */
export const PermissionCodes = {
  CORE_USERS_VIEW: 'core.users.view',
  CORE_USERS_MANAGE: 'core.users.manage',
  CORE_ROLES_VIEW: 'core.roles.view',
  CORE_ROLES_MANAGE: 'core.roles.manage',
  CORE_TENANT_MANAGE: 'core.tenant.manage',
  CORE_SETTINGS_VIEW: 'core.settings.view',
  CORE_SETTINGS_MANAGE: 'core.settings.manage',

  DOCUMENTS_VIEW: 'documents.view',
  DOCUMENTS_CREATE: 'documents.create',
  DOCUMENTS_EDIT: 'documents.edit',
  DOCUMENTS_DELETE: 'documents.delete',
  DOCUMENTS_POST: 'documents.post',
  DOCUMENTS_UNPOST: 'documents.unpost',
  DOCUMENTS_CANCEL: 'documents.cancel',

  PERIODS_VIEW: 'periods.view',
  PERIODS_CLOSE: 'periods.close',
  PERIODS_REOPEN: 'periods.reopen',

  AUDIT_VIEW: 'audit.view',

  CURRENCY_MANAGE: 'currency.manage',
  NUMBERING_MANAGE: 'numbering.manage',

  // Phase 1 — Organization & Business Structure (section 34)
  ORGANIZATION_VIEW: 'organization.view',
  ORGANIZATION_CREATE: 'organization.create',
  ORGANIZATION_EDIT: 'organization.edit',
  ORGANIZATION_DEACTIVATE: 'organization.deactivate',

  BRANCH_VIEW: 'branch.view',
  BRANCH_CREATE: 'branch.create',
  BRANCH_EDIT: 'branch.edit',
  BRANCH_DEACTIVATE: 'branch.deactivate',

  DEPARTMENT_VIEW: 'department.view',
  DEPARTMENT_CREATE: 'department.create',
  DEPARTMENT_EDIT: 'department.edit',
  DEPARTMENT_DEACTIVATE: 'department.deactivate',

  RESPONSIBLE_PERSON_VIEW: 'responsible_person.view',
  RESPONSIBLE_PERSON_MANAGE: 'responsible_person.manage',

  WAREHOUSE_VIEW: 'warehouse.view',
  WAREHOUSE_CREATE: 'warehouse.create',
  WAREHOUSE_EDIT: 'warehouse.edit',
  WAREHOUSE_DEACTIVATE: 'warehouse.deactivate',

  CASHBOX_VIEW: 'cashbox.view',
  CASHBOX_CREATE: 'cashbox.create',
  CASHBOX_EDIT: 'cashbox.edit',
  CASHBOX_DEACTIVATE: 'cashbox.deactivate',

  BANK_ACCOUNT_VIEW: 'bank_account.view',
  BANK_ACCOUNT_CREATE: 'bank_account.create',
  BANK_ACCOUNT_EDIT: 'bank_account.edit',
  BANK_ACCOUNT_DEACTIVATE: 'bank_account.deactivate',

  ACCOUNTING_POLICY_VIEW: 'accounting_policy.view',
  ACCOUNTING_POLICY_MANAGE: 'accounting_policy.manage',

  TAX_PROFILE_VIEW: 'tax_profile.view',
  TAX_PROFILE_MANAGE: 'tax_profile.manage',

  ORGANIZATION_ACCESS_MANAGE: 'organization_access.manage',

  // Phase 2 — Product/Nomenclature master data
  UNIT_OF_MEASURE_VIEW: 'unit_of_measure.view',
  UNIT_OF_MEASURE_CREATE: 'unit_of_measure.create',
  UNIT_OF_MEASURE_EDIT: 'unit_of_measure.edit',
  UNIT_OF_MEASURE_DEACTIVATE: 'unit_of_measure.deactivate',

  PRODUCT_CATEGORY_VIEW: 'product_category.view',
  PRODUCT_CATEGORY_CREATE: 'product_category.create',
  PRODUCT_CATEGORY_EDIT: 'product_category.edit',
  PRODUCT_CATEGORY_DEACTIVATE: 'product_category.deactivate',

  PRODUCT_VIEW: 'product.view',
  PRODUCT_CREATE: 'product.create',
  PRODUCT_EDIT: 'product.edit',
  PRODUCT_DEACTIVATE: 'product.deactivate',

  // Phase 3 — Counterparty Master Data + Pricing
  UNIT_CONVERSION_VIEW: 'unit_conversion.view',
  UNIT_CONVERSION_CREATE: 'unit_conversion.create',
  UNIT_CONVERSION_EDIT: 'unit_conversion.edit',
  UNIT_CONVERSION_DEACTIVATE: 'unit_conversion.deactivate',

  COUNTERPARTY_VIEW: 'counterparty.view',
  COUNTERPARTY_CREATE: 'counterparty.create',
  COUNTERPARTY_EDIT: 'counterparty.edit',
  COUNTERPARTY_DEACTIVATE: 'counterparty.deactivate',
  COUNTERPARTY_APPROVE: 'counterparty.approve',
  COUNTERPARTY_RISK_MANAGE: 'counterparty.risk.manage',

  // Counterparty contracts / amendments / documents ("Kontragentlər" module)
  CONTRACT_VIEW: 'contract.view',
  CONTRACT_CREATE: 'contract.create',
  CONTRACT_EDIT: 'contract.edit',
  CONTRACT_APPROVE: 'contract.approve',
  CONTRACT_AMENDMENT_CREATE: 'contract.amendment.create',
  CONTRACT_AMENDMENT_EDIT: 'contract.amendment.edit',
  CONTRACT_AMENDMENT_APPROVE: 'contract.amendment.approve',
  CONTRACT_DOCUMENT_MANAGE: 'contract.document.manage',

  PRICE_LIST_VIEW: 'price_list.view',
  PRICE_LIST_CREATE: 'price_list.create',
  PRICE_LIST_EDIT: 'price_list.edit',
  PRICE_LIST_DEACTIVATE: 'price_list.deactivate',

  PRODUCT_PRICE_VIEW: 'product_price.view',
  PRODUCT_PRICE_MANAGE: 'product_price.manage',

  // Phase 4 — Sales documents (orders + invoices)
  SALES_ORDER_VIEW: 'sales_order.view',
  SALES_ORDER_CREATE: 'sales_order.create',
  SALES_ORDER_EDIT: 'sales_order.edit',

  SALES_INVOICE_VIEW: 'sales_invoice.view',
  SALES_INVOICE_CREATE: 'sales_invoice.create',
  SALES_INVOICE_EDIT: 'sales_invoice.edit',

  // Accounting Core (docx spec Phase 4, section 100)
  ACCOUNTING_CHART_VIEW: 'accounting.chart.view',
  ACCOUNTING_CHART_MANAGE: 'accounting.chart.manage',
  ACCOUNTING_ACCOUNT_VIEW: 'accounting.account.view',
  ACCOUNTING_ACCOUNT_CREATE: 'accounting.account.create',
  ACCOUNTING_ACCOUNT_EDIT: 'accounting.account.edit',
  ACCOUNTING_ACCOUNT_DEACTIVATE: 'accounting.account.deactivate',
  ACCOUNTING_DIMENSION_VIEW: 'accounting.dimension.view',
  ACCOUNTING_DIMENSION_MANAGE: 'accounting.dimension.manage',
  ACCOUNTING_MAPPING_VIEW: 'accounting.mapping.view',
  ACCOUNTING_MAPPING_MANAGE: 'accounting.mapping.manage',
  ACCOUNTING_JOURNAL_VIEW: 'accounting.journal.view',
  ACCOUNTING_JOURNAL_POST: 'accounting.journal.post',
  ACCOUNTING_JOURNAL_UNPOST: 'accounting.journal.unpost',
  ACCOUNTING_JOURNAL_REVERSE: 'accounting.journal.reverse',
  ACCOUNTING_MANUAL_OPERATION_VIEW: 'accounting.manual_operation.view',
  ACCOUNTING_MANUAL_OPERATION_CREATE: 'accounting.manual_operation.create',
  ACCOUNTING_MANUAL_OPERATION_EDIT: 'accounting.manual_operation.edit',
  ACCOUNTING_MANUAL_OPERATION_POST: 'accounting.manual_operation.post',
  ACCOUNTING_MANUAL_OPERATION_UNPOST: 'accounting.manual_operation.unpost',
  ACCOUNTING_OPENING_BALANCE_VIEW: 'accounting.opening_balance.view',
  ACCOUNTING_OPENING_BALANCE_MANAGE: 'accounting.opening_balance.manage',
  ACCOUNTING_POSTING_HISTORY_VIEW: 'accounting.posting_history.view',
  ACCOUNTING_TRIAL_BALANCE_VIEW: 'accounting.trial_balance.view',
  ACCOUNTING_GENERAL_LEDGER_VIEW: 'accounting.general_ledger.view',

  // Tax Engine (docx spec Phase 5, section 97)
  TAX_CONFIG_VIEW: 'tax.config.view',
  TAX_RULE_VIEW: 'tax.rule.view',
  TAX_RULE_CREATE: 'tax.rule.create',
  TAX_RULE_EDIT: 'tax.rule.edit',
  TAX_RULE_APPROVE: 'tax.rule.approve',
  TAX_RULE_ACTIVATE: 'tax.rule.activate',
  TAX_RATE_VIEW: 'tax.rate.view',
  TAX_RATE_MANAGE: 'tax.rate.manage',
  TAX_CATEGORY_VIEW: 'tax.category.view',
  TAX_CATEGORY_MANAGE: 'tax.category.manage',
  TAX_REGISTRATION_VIEW: 'tax.registration.view',
  TAX_REGISTRATION_MANAGE: 'tax.registration.manage',
  TAX_MAPPING_VIEW: 'tax.mapping.view',
  TAX_MAPPING_MANAGE: 'tax.mapping.manage',
  TAX_LEGAL_SOURCE_VIEW: 'tax.legal_source.view',
  TAX_LEGAL_SOURCE_MANAGE: 'tax.legal_source.manage',
  TAX_CALCULATION_VIEW: 'tax.calculation.view',
  TAX_REGISTER_VIEW: 'tax.register.view',
  TAX_OVERRIDE: 'tax.override',
  TAX_PERIOD_VIEW: 'tax.period.view',
  TAX_PERIOD_MANAGE: 'tax.period.manage',

  // Sales Pre-Order & Order Management (docx spec Phase 6, section 100)
  SALES_CUSTOMER_REQUEST_VIEW: 'sales.customer_request.view',
  SALES_CUSTOMER_REQUEST_CREATE: 'sales.customer_request.create',
  SALES_CUSTOMER_REQUEST_EDIT: 'sales.customer_request.edit',
  SALES_CUSTOMER_REQUEST_CANCEL: 'sales.customer_request.cancel',
  SALES_OFFER_VIEW: 'sales.offer.view',
  SALES_OFFER_CREATE: 'sales.offer.create',
  SALES_OFFER_EDIT: 'sales.offer.edit',
  SALES_OFFER_SEND: 'sales.offer.send',
  SALES_OFFER_ACCEPT: 'sales.offer.accept',
  SALES_OFFER_CANCEL: 'sales.offer.cancel',
  SALES_OFFER_CONVERT: 'sales.offer.convert',
  SALES_ORDER_CONFIRM: 'sales.order.confirm',
  SALES_ORDER_CANCEL: 'sales.order.cancel',
  SALES_ORDER_REOPEN: 'sales.order.reopen',
  SALES_ORDER_APPROVE: 'sales.order.approve',
  SALES_ORDER_REJECT: 'sales.order.reject',
  SALES_PRICE_OVERRIDE: 'sales.price.override',
  SALES_DISCOUNT_OVERRIDE: 'sales.discount.override',
  SALES_CREDIT_OVERRIDE: 'sales.credit.override',
  SALES_RESERVATION_VIEW: 'sales.reservation.view',
  SALES_RESERVATION_MANAGE: 'sales.reservation.manage',
  SALES_SHIPMENT_PLAN_VIEW: 'sales.shipment_plan.view',
  SALES_SHIPMENT_PLAN_MANAGE: 'sales.shipment_plan.manage',
  SALES_PAYMENT_SCHEDULE_VIEW: 'sales.payment_schedule.view',
  SALES_FULFILLMENT_VIEW: 'sales.fulfillment.view',
  SALES_ORDER_HOLD_MANAGE: 'sales.order_hold.manage',

  // Sales Execution (docx spec Phase 7, section 84)
  SALES_SHIPMENT_VIEW: 'sales.shipment.view',
  SALES_SHIPMENT_CREATE: 'sales.shipment.create',
  SALES_SHIPMENT_EDIT: 'sales.shipment.edit',
  SALES_SHIPMENT_CANCEL: 'sales.shipment.cancel',
  SALES_INVOICE_REVERSE: 'sales.invoice.reverse',
  SALES_RETURN_VIEW: 'sales.return.view',
  SALES_RETURN_CREATE: 'sales.return.create',
  SALES_RETURN_EDIT: 'sales.return.edit',
  SALES_ACCOUNTING_ENTRIES_VIEW: 'sales.accounting_entries.view',
  SALES_TAX_DETAILS_VIEW: 'sales.tax_details.view',

  // Procurement & Purchase Order Management (docx spec Phase 8, section 92)
  PURCHASE_REQUIREMENT_VIEW: 'purchase.requirement.view',
  PURCHASE_REQUIREMENT_CREATE: 'purchase.requirement.create',
  PURCHASE_REQUIREMENT_EDIT: 'purchase.requirement.edit',
  PURCHASE_REQUIREMENT_CANCEL: 'purchase.requirement.cancel',
  PURCHASE_REQUIREMENT_APPROVE: 'purchase.requirement.approve',
  PURCHASE_REQUIREMENT_REJECT: 'purchase.requirement.reject',
  PURCHASE_ORDER_VIEW: 'purchase.order.view',
  PURCHASE_ORDER_CREATE: 'purchase.order.create',
  PURCHASE_ORDER_EDIT: 'purchase.order.edit',
  PURCHASE_ORDER_APPROVE: 'purchase.order.approve',
  PURCHASE_ORDER_REJECT: 'purchase.order.reject',
  PURCHASE_ORDER_CONFIRM: 'purchase.order.confirm',
  PURCHASE_ORDER_REOPEN: 'purchase.order.reopen',
  PURCHASE_ORDER_CANCEL: 'purchase.order.cancel',
  PURCHASE_PRICE_OVERRIDE: 'purchase.price.override',
  PURCHASE_SUPPLIER_SELECTION_VIEW: 'purchase.supplier_selection.view',
  PURCHASE_SUPPLIER_SELECTION_MANAGE: 'purchase.supplier_selection.manage',
  PURCHASE_EXPECTED_RECEIPT_VIEW: 'purchase.expected_receipt.view',
  PURCHASE_PAYMENT_SCHEDULE_VIEW: 'purchase.payment_schedule.view',
  PURCHASE_PAYMENT_SCHEDULE_MANAGE: 'purchase.payment_schedule.manage',
  PURCHASE_SUPPLY_PLANNING_VIEW: 'purchase.supply_planning.view',
  PURCHASE_SUPPLY_PEGGING_MANAGE: 'purchase.supply_pegging.manage',
  PURCHASE_ORDER_HOLD_MANAGE: 'purchase.order_hold.manage',
  PURCHASE_SUPPLIER_PRODUCT_CODE_VIEW: 'purchase.supplier_product_code.view',
  PURCHASE_SUPPLIER_PRODUCT_CODE_MANAGE: 'purchase.supplier_product_code.manage',

  // Purchase Execution (docx spec Phase 9, section 37) — Goods Receipt,
  // Purchase Invoice, Purchase Return, Additional Purchase Cost. Confirm
  // /reopen/cancel reuse the generic documents.post/unpost/cancel
  // permissions on /documents/<TYPE>/:id/... like every other document
  // type in this codebase (PURCHASE_POST/UNPOST/CANCEL from the spec's
  // own list are intentionally not duplicated here).
  PURCHASE_VIEW: 'purchase_execution.view',
  PURCHASE_CREATE: 'purchase_execution.create',
  PURCHASE_EDIT: 'purchase_execution.edit',
  PURCHASE_RETURN: 'purchase_execution.return',
  PURCHASE_VIEW_ACCOUNTING: 'purchase_execution.view_accounting',
  // Approval workflow increment 2 (docs/APPROVALS.md): price/tax
  // visibility gate on Goods Receipt, plus approve/reject for the
  // over-delivery (WAREHOUSE_SUPERVISOR) and price-variance (ACCOUNTING)
  // approval steps.
  PURCHASE_PRICE_VIEW: 'purchase_execution.price_view',
  PURCHASE_RECEIPT_APPROVE: 'purchase_execution.receipt.approve',
  PURCHASE_RECEIPT_REJECT: 'purchase_execution.receipt.reject',
  PURCHASE_INVOICE_APPROVE: 'purchase_execution.invoice.approve',
  PURCHASE_INVOICE_REJECT: 'purchase_execution.invoice.reject',

  // Warehouse / Stock Engine (docx spec Phase 10, section 65)
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_VIEW_ALL_WAREHOUSES: 'inventory.view_all_warehouses',
  INVENTORY_TRANSFER_CREATE: 'inventory.transfer.create',
  INVENTORY_TRANSFER_POST: 'inventory.transfer.post',
  INVENTORY_TRANSFER_RECEIVE: 'inventory.transfer.receive',
  INVENTORY_INTERNAL_MOVE: 'inventory.internal_move',
  INVENTORY_CONSUME: 'inventory.consume',
  INVENTORY_WRITE_OFF: 'inventory.write_off',
  INVENTORY_WRITE_OFF_APPROVE: 'inventory.write_off.approve',
  INVENTORY_STATUS_CHANGE: 'inventory.status_change',
  INVENTORY_RESERVE: 'inventory.reserve',
  INVENTORY_RELEASE_RESERVATION: 'inventory.release_reservation',
  INVENTORY_OVERRIDE_NEGATIVE: 'inventory.override_negative',
  INVENTORY_VIEW_SERIAL_HISTORY: 'inventory.view_serial_history',
  INVENTORY_VIEW_MOVEMENTS: 'inventory.view_movements',
  INVENTORY_UNPOST: 'inventory.unpost',
  INVENTORY_PERIOD_OVERRIDE: 'inventory.period_override',
  INVENTORY_MANUAL_ADJUSTMENT: 'inventory.manual_adjustment',

  // Inventory Costing Engine (docx spec Phase 11, section 97)
  INVENTORY_COST_VIEW: 'inventory_cost.view',
  INVENTORY_COST_VIEW_LAYERS: 'inventory_cost.view_layers',
  INVENTORY_COST_RECALCULATE: 'inventory_cost.recalculate',
  INVENTORY_COST_FINALIZE: 'inventory_cost.finalize',
  INVENTORY_COST_REOPEN: 'inventory_cost.reopen',
  INVENTORY_COST_ADJUST: 'inventory_cost.adjust',
  INVENTORY_COST_MANUAL_OVERRIDE: 'inventory_cost.manual_override',
  INVENTORY_COST_VIEW_ERRORS: 'inventory_cost.view_errors',
  INVENTORY_COST_VIEW_COGS: 'inventory_cost.view_cogs',
  INVENTORY_COST_VIEW_ACCOUNTING: 'inventory_cost.view_accounting',
  INVENTORY_COST_POLICY_MANAGE: 'inventory_cost.policy_manage',

  // Inventory Count / Stocktaking Engine (docx spec Phase 12, section 75)
  INVENTORY_COUNT_VIEW: 'inventory_count.view',
  INVENTORY_COUNT_CREATE: 'inventory_count.create',
  INVENTORY_COUNT_START: 'inventory_count.start',
  INVENTORY_COUNT_CREATE_SNAPSHOT: 'inventory_count.create_snapshot',
  INVENTORY_COUNT_FREEZE: 'inventory_count.freeze',
  INVENTORY_COUNT_ENTER: 'inventory_count.enter',
  INVENTORY_COUNT_RECOUNT: 'inventory_count.recount',
  INVENTORY_COUNT_REVIEW: 'inventory_count.review',
  INVENTORY_COUNT_APPROVE: 'inventory_count.approve',
  INVENTORY_COUNT_POST_ADJUSTMENT: 'inventory_count.post_adjustment',
  INVENTORY_COUNT_CANCEL: 'inventory_count.cancel',
  INVENTORY_COUNT_VIEW_ACCOUNTING_QTY: 'inventory_count.view_accounting_qty',
  INVENTORY_COUNT_VIEW_COST: 'inventory_count.view_cost',
  INVENTORY_COUNT_OVERRIDE_VARIANCE: 'inventory_count.override_variance',
  INVENTORY_COUNT_CLOSE: 'inventory_count.close',

  // AR/AP Settlement Engine (docx spec Phase 13, section 133)
  SETTLEMENT_VIEW: 'settlement.view',
  SETTLEMENT_VIEW_ALL: 'settlement.view_all',
  SETTLEMENT_ALLOCATE: 'settlement.allocate',
  SETTLEMENT_AUTO_ALLOCATE: 'settlement.auto_allocate',
  SETTLEMENT_REVERSE_ALLOCATION: 'settlement.reverse_allocation',
  SETTLEMENT_APPLY_ADVANCE: 'settlement.apply_advance',
  SETTLEMENT_CREATE_ADJUSTMENT: 'settlement.create_adjustment',
  SETTLEMENT_APPROVE_ADJUSTMENT: 'settlement.approve_adjustment',
  SETTLEMENT_WRITE_OFF: 'settlement.write_off',
  SETTLEMENT_OFFSET: 'settlement.offset',
  SETTLEMENT_RECONCILE: 'settlement.reconcile',
  SETTLEMENT_VIEW_FX: 'settlement.view_fx',
  SETTLEMENT_OVERRIDE_FX: 'settlement.override_fx',
  SETTLEMENT_VIEW_ACCOUNTING: 'settlement.view_accounting',
  SETTLEMENT_OVERRIDE_CONTRACT: 'settlement.override_contract',
  SETTLEMENT_PERIOD_OVERRIDE: 'settlement.period_override',

  // Treasury / Bank Engine (docx spec Phase 14, section 104)
  TREASURY_VIEW: 'treasury.view',
  TREASURY_PAYMENT_REQUEST_CREATE: 'treasury.payment_request.create',
  TREASURY_PAYMENT_REQUEST_APPROVE: 'treasury.payment_request.approve',
  TREASURY_PAYMENT_PLAN: 'treasury.payment_plan',
  TREASURY_VIEW_LIQUIDITY: 'treasury.view_liquidity',
  TREASURY_CREATE_PAYMENT: 'treasury.create_payment',
  TREASURY_POST_PAYMENT: 'treasury.post_payment',
  TREASURY_CANCEL_PAYMENT: 'treasury.cancel_payment',
  TREASURY_IMPORT_STATEMENT: 'treasury.import_statement',
  TREASURY_MATCH_BANK_TRANSACTION: 'treasury.match_bank_transaction',
  TREASURY_RECONCILE_BANK: 'treasury.reconcile_bank',
  TREASURY_CLOSE_RECONCILIATION: 'treasury.close_reconciliation',
  TREASURY_INTERNAL_TRANSFER: 'treasury.internal_transfer',
  TREASURY_FX_CONVERSION: 'treasury.fx_conversion',
  TREASURY_OVERRIDE_MATCH: 'treasury.override_match',
  TREASURY_OVERRIDE_PAYMENT_AMOUNT: 'treasury.override_payment_amount',
  TREASURY_VIEW_BANK_BALANCE: 'treasury.view_bank_balance',
  TREASURY_VIEW_ALL_BANK_ACCOUNTS: 'treasury.view_all_bank_accounts',

  // Cash / Kassa Engine (docx spec Phase 15)
  CASH_VIEW: 'cash.view',
  CASH_VIEW_ALL_DESKS: 'cash.view_all_desks',
  CASH_ASSIGN_CASHIER: 'cash.assign_cashier',
  CASH_CREATE_PAYMENT: 'cash.create_payment',
  CASH_POST_PAYMENT: 'cash.post_payment',
  CASH_CANCEL_PAYMENT: 'cash.cancel_payment',
  CASH_TRANSFER: 'cash.transfer',
  CASH_COUNT: 'cash.count',
  CASH_CREATE_ADJUSTMENT: 'cash.create_adjustment',
  CASH_APPROVE_ADJUSTMENT: 'cash.approve_adjustment',
  CASH_HANDOVER: 'cash.handover',
  CASH_DAILY_CLOSE: 'cash.daily_close',
  CASH_REOPEN_DAY: 'cash.reopen_day',
  CASH_OVERRIDE_LIMIT: 'cash.override_limit',

  // Fixed Assets build (docx spec Phase 16, section 126)
  FIXED_ASSET_VIEW: 'fixed_asset.view',
  FIXED_ASSET_VIEW_COST: 'fixed_asset.view_cost',
  FIXED_ASSET_CREATE: 'fixed_asset.create',
  FIXED_ASSET_ACCEPT: 'fixed_asset.accept',
  FIXED_ASSET_COMMISSION: 'fixed_asset.commission',
  FIXED_ASSET_TRANSFER: 'fixed_asset.transfer',
  FIXED_ASSET_MODERNIZE: 'fixed_asset.modernize',
  FIXED_ASSET_CHANGE_USEFUL_LIFE: 'fixed_asset.change_useful_life',
  FIXED_ASSET_DEPRECIATION_CALCULATE: 'fixed_asset.depreciation_calculate',
  FIXED_ASSET_DEPRECIATION_POST: 'fixed_asset.depreciation_post',
  FIXED_ASSET_IMPAIR: 'fixed_asset.impair',
  FIXED_ASSET_REVALUE: 'fixed_asset.revalue',
  FIXED_ASSET_INVENTORY: 'fixed_asset.inventory',
  FIXED_ASSET_DISPOSE: 'fixed_asset.dispose',
  FIXED_ASSET_WRITE_OFF: 'fixed_asset.write_off',
  FIXED_ASSET_MANUAL_ADJUSTMENT: 'fixed_asset.manual_adjustment',
  FIXED_ASSET_VIEW_ACCOUNTING: 'fixed_asset.view_accounting',
  FIXED_ASSET_PERIOD_OVERRIDE: 'fixed_asset.period_override',

  // HR Core build (docx spec Phase 17, section 80)
  HR_PERSON_VIEW: 'hr.person.view',
  HR_PERSON_CREATE: 'hr.person.create',
  HR_PERSON_EDIT: 'hr.person.edit',
  HR_EMPLOYEE_VIEW: 'hr.employee.view',
  HR_EMPLOYEE_CREATE: 'hr.employee.create',
  HR_EMPLOYMENT_CREATE: 'hr.employment.create',
  HR_HIRE_CREATE: 'hr.hire.create',
  HR_HIRE_POST: 'hr.hire.post',
  HR_TRANSFER_CREATE: 'hr.transfer.create',
  HR_TRANSFER_POST: 'hr.transfer.post',
  HR_TERMINATE_CREATE: 'hr.terminate.create',
  HR_TERMINATE_POST: 'hr.terminate.post',
  HR_CONTRACT_VIEW: 'hr.contract.view',
  HR_CONTRACT_EDIT: 'hr.contract.edit',
  HR_STAFFING_VIEW: 'hr.staffing.view',
  HR_STAFFING_EDIT: 'hr.staffing.edit',
  HR_LEAVE_VIEW: 'hr.leave.view',
  HR_ABSENCE_VIEW: 'hr.absence.view',
  HR_VIEW_PERSONAL_DATA: 'hr.view_personal_data',
  HR_VIEW_SENSITIVE_DATA: 'hr.view_sensitive_data',
  HR_VIEW_HISTORY: 'hr.view_history',
  HR_OVERRIDE_STAFFING_LIMIT: 'hr.override_staffing_limit',

  // Work Time / Timesheet build (docx spec Phase 18, section 100)
  TIME_VIEW: 'time.view',
  TIME_VIEW_OWN: 'time.view_own',
  TIME_VIEW_DEPARTMENT: 'time.view_department',
  TIME_CALENDAR_EDIT: 'time.calendar_edit',
  TIME_SCHEDULE_EDIT: 'time.schedule_edit',
  TIME_ATTENDANCE_IMPORT: 'time.attendance_import',
  TIME_ATTENDANCE_EDIT: 'time.attendance_edit',
  TIME_TIMESHEET_CREATE: 'time.timesheet_create',
  TIME_TIMESHEET_EDIT: 'time.timesheet_edit',
  TIME_TIMESHEET_APPROVE: 'time.timesheet_approve',
  TIME_TIMESHEET_LOCK: 'time.timesheet_lock',
  TIME_TIMESHEET_REOPEN: 'time.timesheet_reopen',
  TIME_OVERTIME_CREATE: 'time.overtime_create',
  TIME_OVERTIME_APPROVE: 'time.overtime_approve',
  TIME_CORRECTION_CREATE: 'time.correction_create',
  TIME_CORRECTION_APPROVE: 'time.correction_approve',
  TIME_VIEW_PAYROLL_INPUT: 'time.view_payroll_input',
  TIME_OVERRIDE_VALIDATION: 'time.override_validation',

  // Payroll build (docx spec Phase 19)
  PAYROLL_VIEW: 'payroll.view',
  PAYROLL_VIEW_OWN: 'payroll.view_own',
  PAYROLL_CONFIG_EDIT: 'payroll.config_edit',
  PAYROLL_COMPENSATION_EDIT: 'payroll.compensation_edit',
  PAYROLL_TAX_PROFILE_EDIT: 'payroll.tax_profile_edit',
  PAYROLL_VARIABLE_INPUT_CREATE: 'payroll.variable_input_create',
  PAYROLL_EXECUTION_ORDER_EDIT: 'payroll.execution_order_edit',
  PAYROLL_PERIOD_MANAGE: 'payroll.period_manage',
  PAYROLL_CALCULATE: 'payroll.calculate',
  PAYROLL_APPROVE: 'payroll.approve',
  PAYROLL_POST: 'payroll.post',
  PAYROLL_REOPEN: 'payroll.reopen',
  PAYROLL_CLOSE: 'payroll.close',
  PAYROLL_LIABILITY_MANAGE: 'payroll.liability_manage',
  PAYROLL_RECALCULATION_MANAGE: 'payroll.recalculation_manage',
  PAYROLL_VIEW_PAYSLIP: 'payroll.view_payslip',
  PAYROLL_VIEW_STATUTORY_REPORT: 'payroll.view_statutory_report',

  // Expenses / Cost Centers build (docx spec Phase 20)
  EXPENSE_VIEW: 'expense.view',
  EXPENSE_VIEW_OWN: 'expense.view_own',
  EXPENSE_CONFIG_EDIT: 'expense.config_edit',
  EXPENSE_CLAIM_CREATE: 'expense.claim_create',
  EXPENSE_CLAIM_APPROVE: 'expense.claim_approve',
  EXPENSE_CLAIM_POST: 'expense.claim_post',
  EXPENSE_ALLOCATION_EDIT: 'expense.allocation_edit',
  EXPENSE_COST_ALLOCATION_RUN: 'expense.cost_allocation_run',
  EXPENSE_PREPAID_MANAGE: 'expense.prepaid_manage',
  EXPENSE_BUDGET_MANAGE: 'expense.budget_manage',
  EXPENSE_VIEW_SETTLEMENT: 'expense.view_settlement',

  // Manufacturing / Production build (docx spec Phase 21)
  PRODUCTION_VIEW: 'production.view',
  PRODUCTION_ENGINEERING_EDIT: 'production.engineering_edit',
  PRODUCTION_ORDER_CREATE: 'production.order_create',
  PRODUCTION_ORDER_RELEASE: 'production.order_release',
  PRODUCTION_MATERIAL_ISSUE: 'production.material_issue',
  PRODUCTION_EXECUTION_RECORD: 'production.execution_record',
  PRODUCTION_OUTPUT_RECEIVE: 'production.output_receive',
  PRODUCTION_OVERHEAD_MANAGE: 'production.overhead_manage',
  PRODUCTION_VARIANCE_VIEW: 'production.variance_view',
  PRODUCTION_ORDER_CLOSE: 'production.order_close',

  // Month Close / Period Close Orchestrator build (docx spec Phase 22)
  PERIOD_CLOSE_VIEW: 'period_close.view',
  PERIOD_CLOSE_PREVIEW: 'period_close.preview',
  PERIOD_CLOSE_RUN: 'period_close.run',
  PERIOD_CLOSE_STEP_RUN: 'period_close.step_run',
  PERIOD_CLOSE_RESOLVE_ISSUE: 'period_close.resolve_issue',
  PERIOD_CLOSE_WAIVE_WARNING: 'period_close.waive_warning',
  PERIOD_CLOSE_MANUAL_ADJUSTMENT: 'period_close.manual_adjustment',
  PERIOD_SOFT_CLOSE: 'period_close.soft_close',
  PERIOD_HARD_CLOSE: 'period_close.hard_close',
  PERIOD_REOPEN_REQUEST: 'period_close.reopen_request',
  PERIOD_REOPEN_APPROVE: 'period_close.reopen_approve',
  PERIOD_RECLOSE: 'period_close.reclose',
  PERIOD_VIEW_RECONCILIATION: 'period_close.view_reconciliation',
  PERIOD_VIEW_TAX: 'period_close.view_tax',
  PERIOD_VIEW_PAYROLL: 'period_close.view_payroll',
  PERIOD_VIEW_CLOSE_AUDIT: 'period_close.view_audit',

  // Financial Reporting build (docx spec Phase 23)
  FIN_REPORT_VIEW: 'fin_report.view',
  FIN_REPORT_VIEW_PRELIMINARY: 'fin_report.view_preliminary',
  FIN_REPORT_VIEW_FINAL: 'fin_report.view_final',
  FIN_REPORT_TRIAL_BALANCE: 'fin_report.trial_balance',
  FIN_REPORT_BALANCE_SHEET: 'fin_report.balance_sheet',
  FIN_REPORT_PNL: 'fin_report.pnl',
  FIN_REPORT_CASH_FLOW: 'fin_report.cash_flow',
  FIN_REPORT_EQUITY: 'fin_report.equity',
  FIN_REPORT_DRILLDOWN: 'fin_report.drilldown',
  FIN_REPORT_SENSITIVE_DRILLDOWN: 'fin_report.sensitive_drilldown',
  FIN_REPORT_MAPPING_VIEW: 'fin_report.mapping_view',
  FIN_REPORT_MAPPING_EDIT: 'fin_report.mapping_edit',
  FIN_REPORT_MAPPING_APPROVE: 'fin_report.mapping_approve',
  FIN_REPORT_LAYOUT_EDIT: 'fin_report.layout_edit',
  FIN_REPORT_GENERATE: 'fin_report.generate',
  FIN_REPORT_APPROVE: 'fin_report.approve',
  FIN_REPORT_FINALIZE: 'fin_report.finalize',
  FIN_REPORT_SIGN: 'fin_report.sign',
  FIN_REPORT_RESTATE: 'fin_report.restate',
  FIN_REPORT_EXPORT: 'fin_report.export',
  FIN_REPORT_GROUP_VIEW: 'fin_report.group_view',

  // Management Reporting build (docx spec Phase 24)
  MGMT_REPORT_VIEW: 'mgmt_report.view',
  MGMT_DASHBOARD_VIEW: 'mgmt_report.dashboard_view',
  MGMT_KPI_VIEW: 'mgmt_report.kpi_view',
  MGMT_PROFITABILITY_VIEW: 'mgmt_report.profitability_view',
  MGMT_CUSTOMER_PROFITABILITY: 'mgmt_report.customer_profitability',
  MGMT_PRODUCT_PROFITABILITY: 'mgmt_report.product_profitability',
  MGMT_COST_CENTER_VIEW: 'mgmt_report.cost_center_view',
  MGMT_PROJECT_PNL: 'mgmt_report.project_pnl',
  MGMT_WORKING_CAPITAL_VIEW: 'mgmt_report.working_capital_view',
  MGMT_PRODUCTION_VIEW: 'mgmt_report.production_view',
  MGMT_WORKFORCE_COST_VIEW: 'mgmt_report.workforce_cost_view',
  MGMT_BUDGET_VIEW: 'mgmt_report.budget_view',
  MGMT_BUDGET_EDIT: 'mgmt_report.budget_edit',
  MGMT_BUDGET_APPROVE: 'mgmt_report.budget_approve',
  MGMT_FORECAST_EDIT: 'mgmt_report.forecast_edit',
  MGMT_SCENARIO_CREATE: 'mgmt_report.scenario_create',
  MGMT_SEMANTIC_MODEL_EDIT: 'mgmt_report.semantic_model_edit',
  MGMT_KPI_EDIT: 'mgmt_report.kpi_edit',
  MGMT_ALLOCATION_EDIT: 'mgmt_report.allocation_edit',
  MGMT_SNAPSHOT_CREATE: 'mgmt_report.snapshot_create',
  MGMT_EXPORT: 'mgmt_report.export',
  MGMT_SENSITIVE_DRILLDOWN: 'mgmt_report.sensitive_drilldown',

  // Audit / Change History / Traceability / Evidence build (docx spec
  // Phase 25) — AUDIT_VIEW itself already exists from Phase 0 (section 27).
  AUDIT_VIEW_ENTITY_HISTORY: 'audit.view_entity_history',
  AUDIT_VIEW_DOCUMENT_HISTORY: 'audit.view_document_history',
  AUDIT_VIEW_POSTING_TRACE: 'audit.view_posting_trace',
  AUDIT_VIEW_CONFIG_HISTORY: 'audit.view_config_history',
  AUDIT_VIEW_SECURITY_EVENTS: 'audit.view_security_events',
  AUDIT_VIEW_SENSITIVE_ACCESS: 'audit.view_sensitive_access',
  AUDIT_VIEW_SENSITIVE_VALUES: 'audit.view_sensitive_values',
  AUDIT_SEARCH_GLOBAL: 'audit.search_global',
  AUDIT_INVESTIGATION_CREATE: 'audit.investigation_create',
  AUDIT_INVESTIGATION_EDIT: 'audit.investigation_edit',
  AUDIT_EVIDENCE_ADD: 'audit.evidence_add',
  AUDIT_EXPORT: 'audit.export',
  AUDIT_EXPORT_SENSITIVE: 'audit.export_sensitive',
  AUDIT_VERIFY_INTEGRITY: 'audit.verify_integrity',
  AUDIT_LEGAL_HOLD_CREATE: 'audit.legal_hold_create',
  AUDIT_LEGAL_HOLD_RELEASE: 'audit.legal_hold_release',
  AUDIT_RETENTION_MANAGE: 'audit.retention_manage',
  AUDIT_ADMIN: 'audit.admin',

  // Workflow / Approval Engine build (docx spec Phase 26)
  WORKFLOW_VIEW: 'workflow.view',
  WORKFLOW_VIEW_OWN: 'workflow.view_own',
  WORKFLOW_VIEW_DEPARTMENT: 'workflow.view_department',
  WORKFLOW_APPROVE: 'workflow.approve',
  WORKFLOW_REJECT: 'workflow.reject',
  WORKFLOW_REQUEST_CHANGE: 'workflow.request_change',
  WORKFLOW_DELEGATE: 'workflow.delegate',
  WORKFLOW_ADMIN: 'workflow.admin',
  WORKFLOW_DEFINITION_VIEW: 'workflow.definition_view',
  WORKFLOW_DEFINITION_EDIT: 'workflow.definition_edit',
  WORKFLOW_DEFINITION_APPROVE: 'workflow.definition_approve',
  WORKFLOW_RESTART: 'workflow.restart',
  WORKFLOW_CANCEL: 'workflow.cancel',
  WORKFLOW_ESCALATE: 'workflow.escalate',
  WORKFLOW_OVERRIDE_SOD: 'workflow.override_sod',
  WORKFLOW_VIEW_AUDIT: 'workflow.view_audit',
  WORKFLOW_VIEW_SENSITIVE: 'workflow.view_sensitive',

  DOC_CHAIN_VIEW: 'doc_chain.view',
  DOC_CHAIN_TYPE_MANAGE: 'doc_chain.type_manage',
  DOC_CHAIN_TRANSFORMATION_MANAGE: 'doc_chain.transformation_manage',
  DOC_CHAIN_TRANSFORMATION_APPROVE: 'doc_chain.transformation_approve',
  CREATE_BASED_ON_PROPOSE: 'doc_chain.create_based_on_propose',
  CREATE_BASED_ON_ACCEPT: 'doc_chain.create_based_on_accept',
  DOC_CHAIN_CLAIM_MANAGE: 'doc_chain.claim_manage',
  DOC_CHAIN_RELATIONSHIP_VIEW: 'doc_chain.relationship_view',
  DOC_CHAIN_LINEAGE_VIEW: 'doc_chain.lineage_view',
  DOC_CHAIN_IMPACT_VIEW: 'doc_chain.impact_view',
  DOC_CHAIN_IMPACT_OVERRIDE: 'doc_chain.impact_override',
  DOC_CHAIN_EXCEPTION_VIEW: 'doc_chain.exception_view',
  DOC_CHAIN_EXCEPTION_RESOLVE: 'doc_chain.exception_resolve',

  INTEGRATION_VIEW: 'integration.view',
  INTEGRATION_ENDPOINT_VIEW: 'integration.endpoint_view',
  INTEGRATION_ENDPOINT_EDIT: 'integration.endpoint_edit',
  INTEGRATION_CONNECTOR_VIEW: 'integration.connector_view',
  INTEGRATION_CONTRACT_VIEW: 'integration.contract_view',
  INTEGRATION_CONTRACT_EDIT: 'integration.contract_edit',
  INTEGRATION_MAPPING_VIEW: 'integration.mapping_view',
  INTEGRATION_MAPPING_EDIT: 'integration.mapping_edit',
  INTEGRATION_MAPPING_APPROVE: 'integration.mapping_approve',
  INTEGRATION_IMPORT_RUN: 'integration.import_run',
  INTEGRATION_IMPORT_COMMIT: 'integration.import_commit',
  INTEGRATION_EXPORT_RUN: 'integration.export_run',
  INTEGRATION_REPLAY: 'integration.replay',
  INTEGRATION_DEADLETTER_RESOLVE: 'integration.deadletter_resolve',
  INTEGRATION_MANUAL_MATCH: 'integration.manual_match',
  INTEGRATION_RECONCILIATION_RUN: 'integration.reconciliation_run',
  INTEGRATION_CREDENTIAL_ROTATE: 'integration.credential_rotate',
  INTEGRATION_VIEW_PAYLOAD: 'integration.view_payload',
  INTEGRATION_VIEW_SENSITIVE_PAYLOAD: 'integration.view_sensitive_payload',
  INTEGRATION_ADMIN: 'integration.admin',

  AI_USE: 'ai.use',
  AI_FINANCIAL_ANALYSIS: 'ai.financial_analysis',
  AI_MANAGEMENT_INSIGHTS: 'ai.management_insights',
  AI_DOCUMENT_ASSIST: 'ai.document_assist',
  AI_MATCHING: 'ai.matching',
  AI_AUDIT_ASSIST: 'ai.audit_assist',
  AI_PAYROLL_EXPLAIN: 'ai.payroll_explain',
  AI_SENSITIVE_CONTEXT: 'ai.sensitive_context',
  AI_ACTION_PROPOSE: 'ai.action_propose',
  AI_ACTION_ACCEPT: 'ai.action_accept',
  AI_HIGH_RISK_PROPOSE: 'ai.high_risk_propose',
  AI_CONFIG_VIEW: 'ai.config_view',
  AI_CONFIG_EDIT: 'ai.config_edit',
  AI_MODEL_APPROVE: 'ai.model_approve',
  AI_PROMPT_APPROVE: 'ai.prompt_approve',
  AI_TOOL_APPROVE: 'ai.tool_approve',
  AI_EVAL_RUN: 'ai.eval_run',
  AI_EVAL_APPROVE: 'ai.eval_approve',
  AI_USAGE_VIEW: 'ai.usage_view',
  AI_AUDIT_VIEW: 'ai.audit_view',
} as const;

export const ALL_PERMISSION_CODES: { code: string; module: string; description: string }[] = [
  { code: PermissionCodes.CORE_USERS_VIEW, module: 'core', description: 'View users in the tenant' },
  { code: PermissionCodes.CORE_USERS_MANAGE, module: 'core', description: 'Manage tenant memberships' },
  { code: PermissionCodes.CORE_ROLES_VIEW, module: 'core', description: 'View roles and permissions' },
  { code: PermissionCodes.CORE_ROLES_MANAGE, module: 'core', description: 'Manage roles and role permissions' },
  { code: PermissionCodes.CORE_TENANT_MANAGE, module: 'core', description: 'Manage tenant-level configuration' },
  { code: PermissionCodes.CORE_SETTINGS_VIEW, module: 'core', description: 'View scoped settings' },
  { code: PermissionCodes.CORE_SETTINGS_MANAGE, module: 'core', description: 'Manage scoped settings' },

  { code: PermissionCodes.DOCUMENTS_VIEW, module: 'documents', description: 'View documents' },
  { code: PermissionCodes.DOCUMENTS_CREATE, module: 'documents', description: 'Create documents' },
  { code: PermissionCodes.DOCUMENTS_EDIT, module: 'documents', description: 'Edit documents' },
  { code: PermissionCodes.DOCUMENTS_DELETE, module: 'documents', description: 'Mark documents for deletion' },
  { code: PermissionCodes.DOCUMENTS_POST, module: 'documents', description: 'Post documents' },
  { code: PermissionCodes.DOCUMENTS_UNPOST, module: 'documents', description: 'Unpost documents' },
  { code: PermissionCodes.DOCUMENTS_CANCEL, module: 'documents', description: 'Cancel documents' },

  { code: PermissionCodes.PERIODS_VIEW, module: 'periods', description: 'View accounting periods' },
  { code: PermissionCodes.PERIODS_CLOSE, module: 'periods', description: 'Close accounting periods' },
  { code: PermissionCodes.PERIODS_REOPEN, module: 'periods', description: 'Reopen accounting periods' },

  { code: PermissionCodes.AUDIT_VIEW, module: 'audit', description: 'View audit events' },

  { code: PermissionCodes.CURRENCY_MANAGE, module: 'currency', description: 'Manage currencies and exchange rates' },
  { code: PermissionCodes.NUMBERING_MANAGE, module: 'numbering', description: 'Manage numbering sequences' },

  { code: PermissionCodes.ORGANIZATION_VIEW, module: 'organization', description: 'View organizations' },
  { code: PermissionCodes.ORGANIZATION_CREATE, module: 'organization', description: 'Create organizations' },
  { code: PermissionCodes.ORGANIZATION_EDIT, module: 'organization', description: 'Edit organizations' },
  { code: PermissionCodes.ORGANIZATION_DEACTIVATE, module: 'organization', description: 'Deactivate organizations' },

  { code: PermissionCodes.BRANCH_VIEW, module: 'branch', description: 'View branches' },
  { code: PermissionCodes.BRANCH_CREATE, module: 'branch', description: 'Create branches' },
  { code: PermissionCodes.BRANCH_EDIT, module: 'branch', description: 'Edit branches' },
  { code: PermissionCodes.BRANCH_DEACTIVATE, module: 'branch', description: 'Deactivate branches' },

  { code: PermissionCodes.DEPARTMENT_VIEW, module: 'department', description: 'View departments' },
  { code: PermissionCodes.DEPARTMENT_CREATE, module: 'department', description: 'Create departments' },
  { code: PermissionCodes.DEPARTMENT_EDIT, module: 'department', description: 'Edit departments' },
  { code: PermissionCodes.DEPARTMENT_DEACTIVATE, module: 'department', description: 'Deactivate departments' },

  { code: PermissionCodes.RESPONSIBLE_PERSON_VIEW, module: 'responsible_person', description: 'View responsible persons' },
  { code: PermissionCodes.RESPONSIBLE_PERSON_MANAGE, module: 'responsible_person', description: 'Manage responsible persons' },

  { code: PermissionCodes.WAREHOUSE_VIEW, module: 'warehouse', description: 'View warehouses' },
  { code: PermissionCodes.WAREHOUSE_CREATE, module: 'warehouse', description: 'Create warehouses' },
  { code: PermissionCodes.WAREHOUSE_EDIT, module: 'warehouse', description: 'Edit warehouses' },
  { code: PermissionCodes.WAREHOUSE_DEACTIVATE, module: 'warehouse', description: 'Deactivate warehouses' },

  { code: PermissionCodes.CASHBOX_VIEW, module: 'cashbox', description: 'View cashboxes' },
  { code: PermissionCodes.CASHBOX_CREATE, module: 'cashbox', description: 'Create cashboxes' },
  { code: PermissionCodes.CASHBOX_EDIT, module: 'cashbox', description: 'Edit cashboxes' },
  { code: PermissionCodes.CASHBOX_DEACTIVATE, module: 'cashbox', description: 'Deactivate cashboxes' },

  { code: PermissionCodes.BANK_ACCOUNT_VIEW, module: 'bank_account', description: 'View bank accounts' },
  { code: PermissionCodes.BANK_ACCOUNT_CREATE, module: 'bank_account', description: 'Create bank accounts' },
  { code: PermissionCodes.BANK_ACCOUNT_EDIT, module: 'bank_account', description: 'Edit bank accounts' },
  { code: PermissionCodes.BANK_ACCOUNT_DEACTIVATE, module: 'bank_account', description: 'Deactivate bank accounts' },

  { code: PermissionCodes.ACCOUNTING_POLICY_VIEW, module: 'accounting_policy', description: 'View accounting policies' },
  { code: PermissionCodes.ACCOUNTING_POLICY_MANAGE, module: 'accounting_policy', description: 'Manage accounting policies' },

  { code: PermissionCodes.TAX_PROFILE_VIEW, module: 'tax_profile', description: 'View tax profiles' },
  { code: PermissionCodes.TAX_PROFILE_MANAGE, module: 'tax_profile', description: 'Manage tax profiles' },

  { code: PermissionCodes.ORGANIZATION_ACCESS_MANAGE, module: 'organization_access', description: 'Grant/revoke organization access' },

  { code: PermissionCodes.UNIT_OF_MEASURE_VIEW, module: 'unit_of_measure', description: 'View units of measure' },
  { code: PermissionCodes.UNIT_OF_MEASURE_CREATE, module: 'unit_of_measure', description: 'Create units of measure' },
  { code: PermissionCodes.UNIT_OF_MEASURE_EDIT, module: 'unit_of_measure', description: 'Edit units of measure' },
  { code: PermissionCodes.UNIT_OF_MEASURE_DEACTIVATE, module: 'unit_of_measure', description: 'Deactivate units of measure' },

  { code: PermissionCodes.PRODUCT_CATEGORY_VIEW, module: 'product_category', description: 'View product categories' },
  { code: PermissionCodes.PRODUCT_CATEGORY_CREATE, module: 'product_category', description: 'Create product categories' },
  { code: PermissionCodes.PRODUCT_CATEGORY_EDIT, module: 'product_category', description: 'Edit product categories' },
  { code: PermissionCodes.PRODUCT_CATEGORY_DEACTIVATE, module: 'product_category', description: 'Deactivate product categories' },

  { code: PermissionCodes.PRODUCT_VIEW, module: 'product', description: 'View products' },
  { code: PermissionCodes.PRODUCT_CREATE, module: 'product', description: 'Create products' },
  { code: PermissionCodes.PRODUCT_EDIT, module: 'product', description: 'Edit products' },
  { code: PermissionCodes.PRODUCT_DEACTIVATE, module: 'product', description: 'Deactivate products' },

  { code: PermissionCodes.UNIT_CONVERSION_VIEW, module: 'unit_conversion', description: 'View unit conversions' },
  { code: PermissionCodes.UNIT_CONVERSION_CREATE, module: 'unit_conversion', description: 'Create unit conversions' },
  { code: PermissionCodes.UNIT_CONVERSION_EDIT, module: 'unit_conversion', description: 'Edit unit conversions' },
  { code: PermissionCodes.UNIT_CONVERSION_DEACTIVATE, module: 'unit_conversion', description: 'Deactivate unit conversions' },

  { code: PermissionCodes.COUNTERPARTY_VIEW, module: 'counterparty', description: 'View counterparties' },
  { code: PermissionCodes.COUNTERPARTY_CREATE, module: 'counterparty', description: 'Create counterparties' },
  { code: PermissionCodes.COUNTERPARTY_EDIT, module: 'counterparty', description: 'Edit counterparties' },
  { code: PermissionCodes.COUNTERPARTY_DEACTIVATE, module: 'counterparty', description: 'Deactivate counterparties' },
  { code: PermissionCodes.COUNTERPARTY_APPROVE, module: 'counterparty', description: 'Approve counterparties' },
  { code: PermissionCodes.COUNTERPARTY_RISK_MANAGE, module: 'counterparty', description: 'Set a counterparty risk status (watch/blacklist)' },

  { code: PermissionCodes.CONTRACT_VIEW, module: 'contract', description: 'View counterparty contracts' },
  { code: PermissionCodes.CONTRACT_CREATE, module: 'contract', description: 'Create counterparty contracts' },
  { code: PermissionCodes.CONTRACT_EDIT, module: 'contract', description: 'Edit counterparty contracts' },
  { code: PermissionCodes.CONTRACT_APPROVE, module: 'contract', description: 'Approve counterparty contracts' },
  { code: PermissionCodes.CONTRACT_AMENDMENT_CREATE, module: 'contract', description: 'Create contract amendments' },
  { code: PermissionCodes.CONTRACT_AMENDMENT_EDIT, module: 'contract', description: 'Edit contract amendments' },
  { code: PermissionCodes.CONTRACT_AMENDMENT_APPROVE, module: 'contract', description: 'Approve contract amendments' },
  { code: PermissionCodes.CONTRACT_DOCUMENT_MANAGE, module: 'contract', description: 'Upload/download/delete contract and amendment documents' },

  { code: PermissionCodes.PRICE_LIST_VIEW, module: 'price_list', description: 'View price lists' },
  { code: PermissionCodes.PRICE_LIST_CREATE, module: 'price_list', description: 'Create price lists' },
  { code: PermissionCodes.PRICE_LIST_EDIT, module: 'price_list', description: 'Edit price lists' },
  { code: PermissionCodes.PRICE_LIST_DEACTIVATE, module: 'price_list', description: 'Deactivate price lists' },

  { code: PermissionCodes.PRODUCT_PRICE_VIEW, module: 'product_price', description: 'View product prices' },
  { code: PermissionCodes.PRODUCT_PRICE_MANAGE, module: 'product_price', description: 'Manage product prices' },

  { code: PermissionCodes.SALES_ORDER_VIEW, module: 'sales_order', description: 'View sales orders' },
  { code: PermissionCodes.SALES_ORDER_CREATE, module: 'sales_order', description: 'Create sales orders' },
  { code: PermissionCodes.SALES_ORDER_EDIT, module: 'sales_order', description: 'Edit sales orders' },

  { code: PermissionCodes.SALES_INVOICE_VIEW, module: 'sales_invoice', description: 'View sales invoices' },
  { code: PermissionCodes.SALES_INVOICE_CREATE, module: 'sales_invoice', description: 'Create sales invoices' },
  { code: PermissionCodes.SALES_INVOICE_EDIT, module: 'sales_invoice', description: 'Edit sales invoices' },

  { code: PermissionCodes.ACCOUNTING_CHART_VIEW, module: 'accounting', description: 'View the chart of accounts' },
  { code: PermissionCodes.ACCOUNTING_CHART_MANAGE, module: 'accounting', description: 'Adopt/manage charts of accounts' },
  { code: PermissionCodes.ACCOUNTING_ACCOUNT_VIEW, module: 'accounting', description: 'View accounts' },
  { code: PermissionCodes.ACCOUNTING_ACCOUNT_CREATE, module: 'accounting', description: 'Create accounts/subaccounts' },
  { code: PermissionCodes.ACCOUNTING_ACCOUNT_EDIT, module: 'accounting', description: 'Edit accounts' },
  { code: PermissionCodes.ACCOUNTING_ACCOUNT_DEACTIVATE, module: 'accounting', description: 'Deactivate accounts' },
  { code: PermissionCodes.ACCOUNTING_DIMENSION_VIEW, module: 'accounting', description: 'View accounting dimensions' },
  { code: PermissionCodes.ACCOUNTING_DIMENSION_MANAGE, module: 'accounting', description: 'Manage accounting dimensions/rules' },
  { code: PermissionCodes.ACCOUNTING_MAPPING_VIEW, module: 'accounting', description: 'View accounting mappings' },
  { code: PermissionCodes.ACCOUNTING_MAPPING_MANAGE, module: 'accounting', description: 'Manage accounting mappings' },
  { code: PermissionCodes.ACCOUNTING_JOURNAL_VIEW, module: 'accounting', description: 'View journal entries' },
  { code: PermissionCodes.ACCOUNTING_JOURNAL_POST, module: 'accounting', description: 'Post journal entries' },
  { code: PermissionCodes.ACCOUNTING_JOURNAL_UNPOST, module: 'accounting', description: 'Unpost journal entries' },
  { code: PermissionCodes.ACCOUNTING_JOURNAL_REVERSE, module: 'accounting', description: 'Reverse posted journal entries' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_VIEW, module: 'accounting', description: 'View manual operations' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_CREATE, module: 'accounting', description: 'Create manual operations' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_EDIT, module: 'accounting', description: 'Edit draft manual operations' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_POST, module: 'accounting', description: 'Post manual operations' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_UNPOST, module: 'accounting', description: 'Unpost manual operations' },
  { code: PermissionCodes.ACCOUNTING_OPENING_BALANCE_VIEW, module: 'accounting', description: 'View opening balances' },
  { code: PermissionCodes.ACCOUNTING_OPENING_BALANCE_MANAGE, module: 'accounting', description: 'Enter opening balances' },
  { code: PermissionCodes.ACCOUNTING_POSTING_HISTORY_VIEW, module: 'accounting', description: 'View posting run history' },
  { code: PermissionCodes.ACCOUNTING_TRIAL_BALANCE_VIEW, module: 'accounting', description: 'View the trial balance' },
  { code: PermissionCodes.ACCOUNTING_GENERAL_LEDGER_VIEW, module: 'accounting', description: 'View the general ledger' },

  { code: PermissionCodes.TAX_CONFIG_VIEW, module: 'tax', description: 'View tax configuration' },
  { code: PermissionCodes.TAX_RULE_VIEW, module: 'tax', description: 'View tax rules' },
  { code: PermissionCodes.TAX_RULE_CREATE, module: 'tax', description: 'Create tax rules' },
  { code: PermissionCodes.TAX_RULE_EDIT, module: 'tax', description: 'Edit tax rules' },
  { code: PermissionCodes.TAX_RULE_APPROVE, module: 'tax', description: 'Approve tax rules' },
  { code: PermissionCodes.TAX_RULE_ACTIVATE, module: 'tax', description: 'Activate tax rules' },
  { code: PermissionCodes.TAX_RATE_VIEW, module: 'tax', description: 'View tax rates' },
  { code: PermissionCodes.TAX_RATE_MANAGE, module: 'tax', description: 'Manage tax rates' },
  { code: PermissionCodes.TAX_CATEGORY_VIEW, module: 'tax', description: 'View tax categories' },
  { code: PermissionCodes.TAX_CATEGORY_MANAGE, module: 'tax', description: 'Manage tax categories' },
  { code: PermissionCodes.TAX_REGISTRATION_VIEW, module: 'tax', description: 'View tax registrations' },
  { code: PermissionCodes.TAX_REGISTRATION_MANAGE, module: 'tax', description: 'Manage tax registrations' },
  { code: PermissionCodes.TAX_MAPPING_VIEW, module: 'tax', description: 'View tax accounting mappings' },
  { code: PermissionCodes.TAX_MAPPING_MANAGE, module: 'tax', description: 'Manage tax accounting mappings' },
  { code: PermissionCodes.TAX_LEGAL_SOURCE_VIEW, module: 'tax', description: 'View tax legal sources' },
  { code: PermissionCodes.TAX_LEGAL_SOURCE_MANAGE, module: 'tax', description: 'Manage tax legal sources' },
  { code: PermissionCodes.TAX_CALCULATION_VIEW, module: 'tax', description: 'Preview/calculate tax' },
  { code: PermissionCodes.TAX_REGISTER_VIEW, module: 'tax', description: 'View the tax register' },
  { code: PermissionCodes.TAX_OVERRIDE, module: 'tax', description: 'Override a calculated tax amount' },
  { code: PermissionCodes.TAX_PERIOD_VIEW, module: 'tax', description: 'View tax periods' },
  { code: PermissionCodes.TAX_PERIOD_MANAGE, module: 'tax', description: 'Manage tax periods' },

  { code: PermissionCodes.SALES_CUSTOMER_REQUEST_VIEW, module: 'sales_preorder', description: 'View customer requests' },
  { code: PermissionCodes.SALES_CUSTOMER_REQUEST_CREATE, module: 'sales_preorder', description: 'Create customer requests' },
  { code: PermissionCodes.SALES_CUSTOMER_REQUEST_EDIT, module: 'sales_preorder', description: 'Edit customer requests' },
  { code: PermissionCodes.SALES_CUSTOMER_REQUEST_CANCEL, module: 'sales_preorder', description: 'Cancel customer requests' },
  { code: PermissionCodes.SALES_OFFER_VIEW, module: 'sales_preorder', description: 'View commercial offers' },
  { code: PermissionCodes.SALES_OFFER_CREATE, module: 'sales_preorder', description: 'Create commercial offers' },
  { code: PermissionCodes.SALES_OFFER_EDIT, module: 'sales_preorder', description: 'Edit commercial offers' },
  { code: PermissionCodes.SALES_OFFER_SEND, module: 'sales_preorder', description: 'Send a commercial offer to the customer' },
  { code: PermissionCodes.SALES_OFFER_ACCEPT, module: 'sales_preorder', description: 'Mark a commercial offer accepted/rejected' },
  { code: PermissionCodes.SALES_OFFER_CANCEL, module: 'sales_preorder', description: 'Cancel a commercial offer' },
  { code: PermissionCodes.SALES_OFFER_CONVERT, module: 'sales_preorder', description: 'Convert an offer into a customer order' },
  { code: PermissionCodes.SALES_ORDER_CONFIRM, module: 'sales_preorder', description: 'Confirm a customer order' },
  { code: PermissionCodes.SALES_ORDER_APPROVE, module: 'sales_preorder', description: 'Approve one step of a sales order approval chain' },
  { code: PermissionCodes.SALES_ORDER_REJECT, module: 'sales_preorder', description: 'Reject a sales order approval' },
  { code: PermissionCodes.SALES_ORDER_CANCEL, module: 'sales_preorder', description: 'Cancel a customer order' },
  { code: PermissionCodes.SALES_ORDER_REOPEN, module: 'sales_preorder', description: 'Reopen (unconfirm) a customer order' },
  { code: PermissionCodes.SALES_PRICE_OVERRIDE, module: 'sales_preorder', description: 'Override a resolved price' },
  { code: PermissionCodes.SALES_DISCOUNT_OVERRIDE, module: 'sales_preorder', description: 'Override a line/document discount' },
  { code: PermissionCodes.SALES_CREDIT_OVERRIDE, module: 'sales_preorder', description: 'Override a blocked credit check' },
  { code: PermissionCodes.SALES_RESERVATION_VIEW, module: 'sales_preorder', description: 'View stock reservations' },
  { code: PermissionCodes.SALES_RESERVATION_MANAGE, module: 'sales_preorder', description: 'Create/release stock reservations' },
  { code: PermissionCodes.SALES_SHIPMENT_PLAN_VIEW, module: 'sales_preorder', description: 'View shipment plans' },
  { code: PermissionCodes.SALES_SHIPMENT_PLAN_MANAGE, module: 'sales_preorder', description: 'Create/manage shipment plans' },
  { code: PermissionCodes.SALES_PAYMENT_SCHEDULE_VIEW, module: 'sales_preorder', description: 'View order payment schedules' },
  { code: PermissionCodes.SALES_FULFILLMENT_VIEW, module: 'sales_preorder', description: 'View order fulfillment status' },
  { code: PermissionCodes.SALES_ORDER_HOLD_MANAGE, module: 'sales_preorder', description: 'Place/release order holds' },

  { code: PermissionCodes.SALES_SHIPMENT_VIEW, module: 'sales_execution', description: 'View shipments' },
  { code: PermissionCodes.SALES_SHIPMENT_CREATE, module: 'sales_execution', description: 'Create shipments' },
  { code: PermissionCodes.SALES_SHIPMENT_EDIT, module: 'sales_execution', description: 'Edit shipments' },
  { code: PermissionCodes.SALES_SHIPMENT_CANCEL, module: 'sales_execution', description: 'Cancel shipments' },
  { code: PermissionCodes.SALES_INVOICE_REVERSE, module: 'sales_execution', description: 'Reverse a posted sales invoice' },
  { code: PermissionCodes.SALES_RETURN_VIEW, module: 'sales_execution', description: 'View sales returns' },
  { code: PermissionCodes.SALES_RETURN_CREATE, module: 'sales_execution', description: 'Create sales returns' },
  { code: PermissionCodes.SALES_RETURN_EDIT, module: 'sales_execution', description: 'Edit sales returns' },
  { code: PermissionCodes.SALES_ACCOUNTING_ENTRIES_VIEW, module: 'sales_execution', description: 'View accounting entries behind a sales document' },
  { code: PermissionCodes.SALES_TAX_DETAILS_VIEW, module: 'sales_execution', description: 'View tax calculation details behind a sales document' },

  { code: PermissionCodes.PURCHASE_REQUIREMENT_VIEW, module: 'procurement', description: 'View purchase requirements' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_CREATE, module: 'procurement', description: 'Create purchase requirements' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_EDIT, module: 'procurement', description: 'Edit purchase requirements' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_CANCEL, module: 'procurement', description: 'Cancel purchase requirements' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_APPROVE, module: 'procurement', description: 'Approve a purchase requirement (department head)' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_REJECT, module: 'procurement', description: 'Reject a purchase requirement' },
  { code: PermissionCodes.PURCHASE_ORDER_VIEW, module: 'procurement', description: 'View purchase orders' },
  { code: PermissionCodes.PURCHASE_ORDER_CREATE, module: 'procurement', description: 'Create purchase orders' },
  { code: PermissionCodes.PURCHASE_ORDER_EDIT, module: 'procurement', description: 'Edit purchase orders' },
  { code: PermissionCodes.PURCHASE_ORDER_APPROVE, module: 'procurement', description: 'Approve one step of a purchase order approval chain' },
  { code: PermissionCodes.PURCHASE_ORDER_REJECT, module: 'procurement', description: 'Reject a purchase order approval' },
  { code: PermissionCodes.PURCHASE_ORDER_CONFIRM, module: 'procurement', description: 'Confirm a purchase order (commercial commitment)' },
  { code: PermissionCodes.PURCHASE_ORDER_REOPEN, module: 'procurement', description: 'Reopen (unconfirm) a purchase order' },
  { code: PermissionCodes.PURCHASE_ORDER_CANCEL, module: 'procurement', description: 'Cancel a purchase order' },
  { code: PermissionCodes.PURCHASE_PRICE_OVERRIDE, module: 'procurement', description: 'Override a resolved purchase price' },
  { code: PermissionCodes.PURCHASE_SUPPLIER_SELECTION_VIEW, module: 'procurement', description: 'View supplier selection candidates' },
  { code: PermissionCodes.PURCHASE_SUPPLIER_SELECTION_MANAGE, module: 'procurement', description: 'Select/change a purchase order supplier' },
  { code: PermissionCodes.PURCHASE_EXPECTED_RECEIPT_VIEW, module: 'procurement', description: 'View expected supply/receipts' },
  { code: PermissionCodes.PURCHASE_PAYMENT_SCHEDULE_VIEW, module: 'procurement', description: 'View purchase order payment schedules' },
  { code: PermissionCodes.PURCHASE_PAYMENT_SCHEDULE_MANAGE, module: 'procurement', description: 'Generate purchase order payment schedules' },
  { code: PermissionCodes.PURCHASE_SUPPLY_PLANNING_VIEW, module: 'procurement', description: 'View demand coverage / supply planning' },
  { code: PermissionCodes.PURCHASE_SUPPLY_PEGGING_MANAGE, module: 'procurement', description: 'Create/remove demand-supply pegs' },
  { code: PermissionCodes.PURCHASE_ORDER_HOLD_MANAGE, module: 'procurement', description: 'Place/release purchase order holds' },
  { code: PermissionCodes.PURCHASE_SUPPLIER_PRODUCT_CODE_VIEW, module: 'procurement', description: 'View supplier product code mappings' },
  { code: PermissionCodes.PURCHASE_SUPPLIER_PRODUCT_CODE_MANAGE, module: 'procurement', description: 'Manage supplier product code mappings' },

  { code: PermissionCodes.PURCHASE_VIEW, module: 'purchase_execution', description: 'View goods receipts, purchase invoices, returns, and additional costs' },
  { code: PermissionCodes.PURCHASE_CREATE, module: 'purchase_execution', description: 'Create goods receipts, purchase invoices, and additional costs' },
  { code: PermissionCodes.PURCHASE_EDIT, module: 'purchase_execution', description: 'Edit draft goods receipts and purchase invoices' },
  { code: PermissionCodes.PURCHASE_RETURN, module: 'purchase_execution', description: 'Create purchase returns' },
  { code: PermissionCodes.PURCHASE_VIEW_ACCOUNTING, module: 'purchase_execution', description: 'View purchase reports and accounting entries' },
  { code: PermissionCodes.PURCHASE_PRICE_VIEW, module: 'purchase_execution', description: 'View and override price/tax/monetary fields on goods receipts' },
  { code: PermissionCodes.PURCHASE_RECEIPT_APPROVE, module: 'purchase_execution', description: 'Approve an over-delivery on a goods receipt' },
  { code: PermissionCodes.PURCHASE_RECEIPT_REJECT, module: 'purchase_execution', description: 'Reject an over-delivery on a goods receipt' },
  { code: PermissionCodes.PURCHASE_INVOICE_APPROVE, module: 'purchase_execution', description: 'Approve a purchase invoice price variance' },
  { code: PermissionCodes.PURCHASE_INVOICE_REJECT, module: 'purchase_execution', description: 'Reject a purchase invoice price variance' },

  { code: PermissionCodes.INVENTORY_VIEW, module: 'inventory', description: 'View stock balances and movements for accessible warehouses' },
  { code: PermissionCodes.INVENTORY_VIEW_ALL_WAREHOUSES, module: 'inventory', description: 'View stock across all warehouses, not just assigned ones' },
  { code: PermissionCodes.INVENTORY_TRANSFER_CREATE, module: 'inventory', description: 'Create warehouse transfers' },
  { code: PermissionCodes.INVENTORY_TRANSFER_POST, module: 'inventory', description: 'Post/ship warehouse transfers' },
  { code: PermissionCodes.INVENTORY_TRANSFER_RECEIVE, module: 'inventory', description: 'Receive warehouse transfers at the destination' },
  { code: PermissionCodes.INVENTORY_INTERNAL_MOVE, module: 'inventory', description: 'Move stock between locations within a warehouse' },
  { code: PermissionCodes.INVENTORY_CONSUME, module: 'inventory', description: 'Post internal consumption documents' },
  { code: PermissionCodes.INVENTORY_WRITE_OFF, module: 'inventory', description: 'Create write-off/surplus inventory adjustments' },
  { code: PermissionCodes.INVENTORY_WRITE_OFF_APPROVE, module: 'inventory', description: 'Approve/post inventory adjustments' },
  { code: PermissionCodes.INVENTORY_STATUS_CHANGE, module: 'inventory', description: 'Transfer stock between quality/inventory statuses' },
  { code: PermissionCodes.INVENTORY_RESERVE, module: 'inventory', description: 'Reserve stock' },
  { code: PermissionCodes.INVENTORY_RELEASE_RESERVATION, module: 'inventory', description: 'Release stock reservations' },
  { code: PermissionCodes.INVENTORY_OVERRIDE_NEGATIVE, module: 'inventory', description: 'Override negative-stock blocking' },
  { code: PermissionCodes.INVENTORY_VIEW_SERIAL_HISTORY, module: 'inventory', description: 'View full movement history for a serial number' },
  { code: PermissionCodes.INVENTORY_VIEW_MOVEMENTS, module: 'inventory', description: 'View the inventory movement register' },
  { code: PermissionCodes.INVENTORY_UNPOST, module: 'inventory', description: 'Unpost inventory documents' },
  { code: PermissionCodes.INVENTORY_PERIOD_OVERRIDE, module: 'inventory', description: 'Post inventory documents into a closed period' },
  { code: PermissionCodes.INVENTORY_MANUAL_ADJUSTMENT, module: 'inventory', description: 'Manually adjust stock outside the normal document flow' },

  { code: PermissionCodes.INVENTORY_COST_VIEW, module: 'inventory_cost', description: 'View inventory valuation' },
  { code: PermissionCodes.INVENTORY_COST_VIEW_LAYERS, module: 'inventory_cost', description: 'View FIFO cost layers' },
  { code: PermissionCodes.INVENTORY_COST_RECALCULATE, module: 'inventory_cost', description: 'Trigger inventory cost recalculation' },
  { code: PermissionCodes.INVENTORY_COST_FINALIZE, module: 'inventory_cost', description: 'Finalize an inventory costing period' },
  { code: PermissionCodes.INVENTORY_COST_REOPEN, module: 'inventory_cost', description: 'Reopen a finalized inventory costing period' },
  { code: PermissionCodes.INVENTORY_COST_ADJUST, module: 'inventory_cost', description: 'Create inventory cost adjustments' },
  { code: PermissionCodes.INVENTORY_COST_MANUAL_OVERRIDE, module: 'inventory_cost', description: 'Manually override a calculated cost' },
  { code: PermissionCodes.INVENTORY_COST_VIEW_ERRORS, module: 'inventory_cost', description: 'View costing errors' },
  { code: PermissionCodes.INVENTORY_COST_VIEW_COGS, module: 'inventory_cost', description: 'View COGS reports' },
  { code: PermissionCodes.INVENTORY_COST_VIEW_ACCOUNTING, module: 'inventory_cost', description: 'View costing accounting entries' },
  { code: PermissionCodes.INVENTORY_COST_POLICY_MANAGE, module: 'inventory_cost', description: 'Manage inventory costing policies' },

  { code: PermissionCodes.INVENTORY_COUNT_VIEW, module: 'inventory_count', description: 'View inventory count plans, sessions, and variances' },
  { code: PermissionCodes.INVENTORY_COUNT_CREATE, module: 'inventory_count', description: 'Create inventory count plans and sessions' },
  { code: PermissionCodes.INVENTORY_COUNT_START, module: 'inventory_count', description: 'Start an inventory count session' },
  { code: PermissionCodes.INVENTORY_COUNT_CREATE_SNAPSHOT, module: 'inventory_count', description: 'Generate the authoritative stock snapshot for a session' },
  { code: PermissionCodes.INVENTORY_COUNT_FREEZE, module: 'inventory_count', description: 'Freeze/unfreeze warehouse movements for a count session' },
  { code: PermissionCodes.INVENTORY_COUNT_ENTER, module: 'inventory_count', description: 'Record physical count entries' },
  { code: PermissionCodes.INVENTORY_COUNT_RECOUNT, module: 'inventory_count', description: 'Request/complete a recount' },
  { code: PermissionCodes.INVENTORY_COUNT_REVIEW, module: 'inventory_count', description: 'Review calculated variances' },
  { code: PermissionCodes.INVENTORY_COUNT_APPROVE, module: 'inventory_count', description: 'Approve a variance decision' },
  { code: PermissionCodes.INVENTORY_COUNT_POST_ADJUSTMENT, module: 'inventory_count', description: 'Post the stock/accounting adjustment resulting from a count' },
  { code: PermissionCodes.INVENTORY_COUNT_CANCEL, module: 'inventory_count', description: 'Cancel an inventory count session' },
  { code: PermissionCodes.INVENTORY_COUNT_VIEW_ACCOUNTING_QTY, module: 'inventory_count', description: 'View accounting quantity during a blind count' },
  { code: PermissionCodes.INVENTORY_COUNT_VIEW_COST, module: 'inventory_count', description: 'View stock value/cost during a count' },
  { code: PermissionCodes.INVENTORY_COUNT_OVERRIDE_VARIANCE, module: 'inventory_count', description: 'Override a calculated variance or its cost' },
  { code: PermissionCodes.INVENTORY_COUNT_CLOSE, module: 'inventory_count', description: 'Close a reconciled inventory count session' },

  { code: PermissionCodes.SETTLEMENT_VIEW, module: 'settlement', description: 'View settlement open items, ageing, and balances' },
  { code: PermissionCodes.SETTLEMENT_VIEW_ALL, module: 'settlement', description: 'View/create settlement payments across all counterparties' },
  { code: PermissionCodes.SETTLEMENT_ALLOCATE, module: 'settlement', description: 'Manually allocate a payment to open items' },
  { code: PermissionCodes.SETTLEMENT_AUTO_ALLOCATE, module: 'settlement', description: 'Trigger automatic payment allocation' },
  { code: PermissionCodes.SETTLEMENT_REVERSE_ALLOCATION, module: 'settlement', description: 'Reverse a payment allocation' },
  { code: PermissionCodes.SETTLEMENT_APPLY_ADVANCE, module: 'settlement', description: 'Apply a customer/supplier advance to an open item' },
  { code: PermissionCodes.SETTLEMENT_CREATE_ADJUSTMENT, module: 'settlement', description: 'Create a debt adjustment' },
  { code: PermissionCodes.SETTLEMENT_APPROVE_ADJUSTMENT, module: 'settlement', description: 'Approve a debt adjustment' },
  { code: PermissionCodes.SETTLEMENT_WRITE_OFF, module: 'settlement', description: 'Write off a receivable/payable' },
  { code: PermissionCodes.SETTLEMENT_OFFSET, module: 'settlement', description: 'Create/post a settlement offset' },
  { code: PermissionCodes.SETTLEMENT_RECONCILE, module: 'settlement', description: 'Generate/confirm/close a counterparty reconciliation statement' },
  { code: PermissionCodes.SETTLEMENT_VIEW_FX, module: 'settlement', description: 'View realized FX details on an allocation' },
  { code: PermissionCodes.SETTLEMENT_OVERRIDE_FX, module: 'settlement', description: 'Manually override an exchange rate used in settlement' },
  { code: PermissionCodes.SETTLEMENT_VIEW_ACCOUNTING, module: 'settlement', description: 'View accounting entries behind a settlement event' },
  { code: PermissionCodes.SETTLEMENT_OVERRIDE_CONTRACT, module: 'settlement', description: 'Reclassify an open item to a different contract' },
  { code: PermissionCodes.SETTLEMENT_PERIOD_OVERRIDE, module: 'settlement', description: 'Post a settlement document into a closed period' },

  { code: PermissionCodes.TREASURY_VIEW, module: 'treasury', description: 'View treasury/bank data' },
  { code: PermissionCodes.TREASURY_PAYMENT_REQUEST_CREATE, module: 'treasury', description: 'Create/submit/cancel payment requests' },
  { code: PermissionCodes.TREASURY_PAYMENT_REQUEST_APPROVE, module: 'treasury', description: 'Approve/reject payment requests' },
  { code: PermissionCodes.TREASURY_PAYMENT_PLAN, module: 'treasury', description: 'Manage the payment calendar and payment instructions' },
  { code: PermissionCodes.TREASURY_VIEW_LIQUIDITY, module: 'treasury', description: 'View liquidity forecasts' },
  { code: PermissionCodes.TREASURY_CREATE_PAYMENT, module: 'treasury', description: 'Create bank payments/fees' },
  { code: PermissionCodes.TREASURY_POST_PAYMENT, module: 'treasury', description: 'Post a bank payment' },
  { code: PermissionCodes.TREASURY_CANCEL_PAYMENT, module: 'treasury', description: 'Unpost/cancel a bank payment' },
  { code: PermissionCodes.TREASURY_IMPORT_STATEMENT, module: 'treasury', description: 'Import a bank statement' },
  { code: PermissionCodes.TREASURY_MATCH_BANK_TRANSACTION, module: 'treasury', description: 'Match a bank statement line to an ERP document' },
  { code: PermissionCodes.TREASURY_RECONCILE_BANK, module: 'treasury', description: 'Run a bank reconciliation' },
  { code: PermissionCodes.TREASURY_CLOSE_RECONCILIATION, module: 'treasury', description: 'Close/reopen a bank reconciliation' },
  { code: PermissionCodes.TREASURY_INTERNAL_TRANSFER, module: 'treasury', description: 'Create/complete internal bank transfers' },
  { code: PermissionCodes.TREASURY_FX_CONVERSION, module: 'treasury', description: 'Create FX conversions' },
  { code: PermissionCodes.TREASURY_OVERRIDE_MATCH, module: 'treasury', description: 'Reverse/override a bank transaction match' },
  { code: PermissionCodes.TREASURY_OVERRIDE_PAYMENT_AMOUNT, module: 'treasury', description: 'Override a payment amount beyond its approved request' },
  { code: PermissionCodes.TREASURY_VIEW_BANK_BALANCE, module: 'treasury', description: 'View bank account balances' },
  { code: PermissionCodes.TREASURY_VIEW_ALL_BANK_ACCOUNTS, module: 'treasury', description: 'View all bank accounts, not just assigned ones' },

  { code: PermissionCodes.CASH_VIEW, module: 'cash', description: 'View cash desk data, balances, and documents' },
  { code: PermissionCodes.CASH_VIEW_ALL_DESKS, module: 'cash', description: 'View/create cash documents across all cash desks' },
  { code: PermissionCodes.CASH_ASSIGN_CASHIER, module: 'cash', description: 'Assign/end a cashier assignment on a cash desk' },
  { code: PermissionCodes.CASH_CREATE_PAYMENT, module: 'cash', description: 'Create a cash receipt/expense order' },
  { code: PermissionCodes.CASH_POST_PAYMENT, module: 'cash', description: 'Post a cash receipt/expense order' },
  { code: PermissionCodes.CASH_CANCEL_PAYMENT, module: 'cash', description: 'Unpost/cancel a cash receipt/expense order' },
  { code: PermissionCodes.CASH_TRANSFER, module: 'cash', description: 'Create/receive a cash desk transfer' },
  { code: PermissionCodes.CASH_COUNT, module: 'cash', description: 'Perform a physical cash count' },
  { code: PermissionCodes.CASH_CREATE_ADJUSTMENT, module: 'cash', description: 'Create a cash count adjustment' },
  { code: PermissionCodes.CASH_APPROVE_ADJUSTMENT, module: 'cash', description: 'Post/approve a cash count adjustment' },
  { code: PermissionCodes.CASH_HANDOVER, module: 'cash', description: 'Initiate/resolve/complete a cashier handover' },
  { code: PermissionCodes.CASH_DAILY_CLOSE, module: 'cash', description: 'Close a cash desk business day' },
  { code: PermissionCodes.CASH_REOPEN_DAY, module: 'cash', description: 'Reopen a closed cash day' },
  { code: PermissionCodes.CASH_OVERRIDE_LIMIT, module: 'cash', description: 'Override a cash desk max-limit or negative-balance policy warning' },

  { code: PermissionCodes.FIXED_ASSET_VIEW, module: 'fixed_asset', description: 'View fixed asset register and documents' },
  { code: PermissionCodes.FIXED_ASSET_VIEW_COST, module: 'fixed_asset', description: 'View fixed asset cost/depreciation figures' },
  { code: PermissionCodes.FIXED_ASSET_CREATE, module: 'fixed_asset', description: 'Create acquisition candidates, CIP projects, and capitalize assets' },
  { code: PermissionCodes.FIXED_ASSET_ACCEPT, module: 'fixed_asset', description: 'Accept/capitalize a fixed asset' },
  { code: PermissionCodes.FIXED_ASSET_COMMISSION, module: 'fixed_asset', description: 'Commission a fixed asset' },
  { code: PermissionCodes.FIXED_ASSET_TRANSFER, module: 'fixed_asset', description: 'Transfer a fixed asset between department/location/responsible person' },
  { code: PermissionCodes.FIXED_ASSET_MODERNIZE, module: 'fixed_asset', description: 'Record a fixed asset modernization/improvement' },
  { code: PermissionCodes.FIXED_ASSET_CHANGE_USEFUL_LIFE, module: 'fixed_asset', description: 'Change a fixed asset useful life/residual value/depreciation method' },
  { code: PermissionCodes.FIXED_ASSET_DEPRECIATION_CALCULATE, module: 'fixed_asset', description: 'Preview/calculate a depreciation run' },
  { code: PermissionCodes.FIXED_ASSET_DEPRECIATION_POST, module: 'fixed_asset', description: 'Post/reverse a depreciation run' },
  { code: PermissionCodes.FIXED_ASSET_IMPAIR, module: 'fixed_asset', description: 'Record a fixed asset impairment or reversal' },
  { code: PermissionCodes.FIXED_ASSET_REVALUE, module: 'fixed_asset', description: 'Record a fixed asset revaluation' },
  { code: PermissionCodes.FIXED_ASSET_INVENTORY, module: 'fixed_asset', description: 'Run a fixed asset physical inventory count' },
  { code: PermissionCodes.FIXED_ASSET_DISPOSE, module: 'fixed_asset', description: 'Dispose/sell a fixed asset' },
  { code: PermissionCodes.FIXED_ASSET_WRITE_OFF, module: 'fixed_asset', description: 'Write off a fixed asset' },
  { code: PermissionCodes.FIXED_ASSET_MANUAL_ADJUSTMENT, module: 'fixed_asset', description: 'Manually adjust fixed asset cost/subledger data' },
  { code: PermissionCodes.FIXED_ASSET_VIEW_ACCOUNTING, module: 'fixed_asset', description: 'View fixed asset GL postings and reconciliation' },
  { code: PermissionCodes.FIXED_ASSET_PERIOD_OVERRIDE, module: 'fixed_asset', description: 'Override a locked period for a fixed asset transaction' },

  { code: PermissionCodes.HR_PERSON_VIEW, module: 'hr', description: 'View physical person records' },
  { code: PermissionCodes.HR_PERSON_CREATE, module: 'hr', description: 'Create/update physical person records' },
  { code: PermissionCodes.HR_PERSON_EDIT, module: 'hr', description: 'Edit physical person records' },
  { code: PermissionCodes.HR_EMPLOYEE_VIEW, module: 'hr', description: 'View employee records' },
  { code: PermissionCodes.HR_EMPLOYEE_CREATE, module: 'hr', description: 'Create employee records' },
  { code: PermissionCodes.HR_EMPLOYMENT_CREATE, module: 'hr', description: 'View/create employment records' },
  { code: PermissionCodes.HR_HIRE_CREATE, module: 'hr', description: 'Create a hire/rehire document' },
  { code: PermissionCodes.HR_HIRE_POST, module: 'hr', description: 'Post a hire/rehire document' },
  { code: PermissionCodes.HR_TRANSFER_CREATE, module: 'hr', description: 'Create an employee transfer document' },
  { code: PermissionCodes.HR_TRANSFER_POST, module: 'hr', description: 'Post an employee transfer document' },
  { code: PermissionCodes.HR_TERMINATE_CREATE, module: 'hr', description: 'Create a termination document' },
  { code: PermissionCodes.HR_TERMINATE_POST, module: 'hr', description: 'Post a termination document' },
  { code: PermissionCodes.HR_CONTRACT_VIEW, module: 'hr', description: 'View employment contracts' },
  { code: PermissionCodes.HR_CONTRACT_EDIT, module: 'hr', description: 'Create/amend employment contracts' },
  { code: PermissionCodes.HR_STAFFING_VIEW, module: 'hr', description: 'View staffing tables/positions/capacity' },
  { code: PermissionCodes.HR_STAFFING_EDIT, module: 'hr', description: 'Create/edit staffing tables/positions' },
  { code: PermissionCodes.HR_LEAVE_VIEW, module: 'hr', description: 'View/record leave requests' },
  { code: PermissionCodes.HR_ABSENCE_VIEW, module: 'hr', description: 'View/record absences' },
  { code: PermissionCodes.HR_VIEW_PERSONAL_DATA, module: 'hr', description: 'View personal contact/address data' },
  { code: PermissionCodes.HR_VIEW_SENSITIVE_DATA, module: 'hr', description: 'View sensitive data (bank account, personal ID, medical documents)' },
  { code: PermissionCodes.HR_VIEW_HISTORY, module: 'hr', description: 'View HR effective-dated history (assignments, contracts, status)' },
  { code: PermissionCodes.HR_OVERRIDE_STAFFING_LIMIT, module: 'hr', description: 'Override a staffing position capacity block' },

  { code: PermissionCodes.TIME_VIEW, module: 'time', description: 'View work time data across the organization' },
  { code: PermissionCodes.TIME_VIEW_OWN, module: 'time', description: "View one's own attendance/timesheet" },
  { code: PermissionCodes.TIME_VIEW_DEPARTMENT, module: 'time', description: "View one's department's work time data" },
  { code: PermissionCodes.TIME_CALENDAR_EDIT, module: 'time', description: 'Create/edit production calendars' },
  { code: PermissionCodes.TIME_SCHEDULE_EDIT, module: 'time', description: 'Create/edit work schedule templates and shifts' },
  { code: PermissionCodes.TIME_ATTENDANCE_IMPORT, module: 'time', description: 'Import attendance events' },
  { code: PermissionCodes.TIME_ATTENDANCE_EDIT, module: 'time', description: 'Manually edit/review attendance intervals' },
  { code: PermissionCodes.TIME_TIMESHEET_CREATE, module: 'time', description: 'Generate a timesheet' },
  { code: PermissionCodes.TIME_TIMESHEET_EDIT, module: 'time', description: 'Submit a timesheet' },
  { code: PermissionCodes.TIME_TIMESHEET_APPROVE, module: 'time', description: 'Approve a timesheet' },
  { code: PermissionCodes.TIME_TIMESHEET_LOCK, module: 'time', description: 'Lock an approved timesheet' },
  { code: PermissionCodes.TIME_TIMESHEET_REOPEN, module: 'time', description: 'Reopen a locked timesheet' },
  { code: PermissionCodes.TIME_OVERTIME_CREATE, module: 'time', description: 'Request overtime' },
  { code: PermissionCodes.TIME_OVERTIME_APPROVE, module: 'time', description: 'Approve/reject overtime requests' },
  { code: PermissionCodes.TIME_CORRECTION_CREATE, module: 'time', description: 'Create a time entry correction' },
  { code: PermissionCodes.TIME_CORRECTION_APPROVE, module: 'time', description: 'Approve a time entry correction' },
  { code: PermissionCodes.TIME_VIEW_PAYROLL_INPUT, module: 'time', description: 'View/manage the payroll time input register' },
  { code: PermissionCodes.TIME_OVERRIDE_VALIDATION, module: 'time', description: 'Override a work-time validation block' },

  { code: PermissionCodes.PAYROLL_VIEW, module: 'payroll', description: 'View payroll data across the organization' },
  { code: PermissionCodes.PAYROLL_VIEW_OWN, module: 'payroll', description: "View one's own payroll results/payslip" },
  { code: PermissionCodes.PAYROLL_CONFIG_EDIT, module: 'payroll', description: 'Edit rate brackets and earning/deduction definitions' },
  { code: PermissionCodes.PAYROLL_COMPENSATION_EDIT, module: 'payroll', description: 'Assign employee compensation' },
  { code: PermissionCodes.PAYROLL_TAX_PROFILE_EDIT, module: 'payroll', description: 'Assign employee tax profiles' },
  { code: PermissionCodes.PAYROLL_VARIABLE_INPUT_CREATE, module: 'payroll', description: 'Create bonus/allowance variable inputs' },
  { code: PermissionCodes.PAYROLL_EXECUTION_ORDER_EDIT, module: 'payroll', description: 'Create/edit alimony and execution-order deductions' },
  { code: PermissionCodes.PAYROLL_PERIOD_MANAGE, module: 'payroll', description: 'Open/approve/reopen payroll periods' },
  { code: PermissionCodes.PAYROLL_CALCULATE, module: 'payroll', description: 'Run a payroll calculation' },
  { code: PermissionCodes.PAYROLL_APPROVE, module: 'payroll', description: 'Approve a calculated payroll period' },
  { code: PermissionCodes.PAYROLL_POST, module: 'payroll', description: 'Post payroll accounting entries' },
  { code: PermissionCodes.PAYROLL_REOPEN, module: 'payroll', description: 'Reopen a closed/posted payroll period' },
  { code: PermissionCodes.PAYROLL_CLOSE, module: 'payroll', description: 'Close a payroll period' },
  { code: PermissionCodes.PAYROLL_LIABILITY_MANAGE, module: 'payroll', description: 'Allocate/reverse payroll liability payments' },
  { code: PermissionCodes.PAYROLL_RECALCULATION_MANAGE, module: 'payroll', description: 'Flag/resolve payroll recalculation requests' },
  { code: PermissionCodes.PAYROLL_VIEW_PAYSLIP, module: 'payroll', description: 'View an employee payslip' },
  { code: PermissionCodes.PAYROLL_VIEW_STATUTORY_REPORT, module: 'payroll', description: 'View statutory payroll reports' },

  { code: PermissionCodes.EXPENSE_VIEW, module: 'expense', description: 'View expense claims across the organization' },
  { code: PermissionCodes.EXPENSE_VIEW_OWN, module: 'expense', description: "View one's own expense claims" },
  { code: PermissionCodes.EXPENSE_CONFIG_EDIT, module: 'expense', description: 'Edit expense categories, cost centers, allocation drivers/rules' },
  { code: PermissionCodes.EXPENSE_CLAIM_CREATE, module: 'expense', description: 'Create an expense claim' },
  { code: PermissionCodes.EXPENSE_CLAIM_APPROVE, module: 'expense', description: 'Approve/reject expense claim lines' },
  { code: PermissionCodes.EXPENSE_CLAIM_POST, module: 'expense', description: 'Post an approved expense claim' },
  { code: PermissionCodes.EXPENSE_ALLOCATION_EDIT, module: 'expense', description: 'Split an expense line across cost objects' },
  { code: PermissionCodes.EXPENSE_COST_ALLOCATION_RUN, module: 'expense', description: 'Calculate/post a cost allocation run' },
  { code: PermissionCodes.EXPENSE_PREPAID_MANAGE, module: 'expense', description: 'Create/recognize prepaid expenses' },
  { code: PermissionCodes.EXPENSE_BUDGET_MANAGE, module: 'expense', description: 'Set/view expense budgets' },
  { code: PermissionCodes.EXPENSE_VIEW_SETTLEMENT, module: 'expense', description: "View an employee's advance/expense settlement register" },

  { code: PermissionCodes.PRODUCTION_VIEW, module: 'production', description: 'View manufacturing/production data' },
  { code: PermissionCodes.PRODUCTION_ENGINEERING_EDIT, module: 'production', description: 'Create/approve BOMs, routings, and work centers' },
  { code: PermissionCodes.PRODUCTION_ORDER_CREATE, module: 'production', description: 'Create a production order' },
  { code: PermissionCodes.PRODUCTION_ORDER_RELEASE, module: 'production', description: 'Release a production order (explodes material requirements)' },
  { code: PermissionCodes.PRODUCTION_MATERIAL_ISSUE, module: 'production', description: 'Issue/return material against a production order' },
  { code: PermissionCodes.PRODUCTION_EXECUTION_RECORD, module: 'production', description: 'Record operation execution, labor, machine time, and scrap' },
  { code: PermissionCodes.PRODUCTION_OUTPUT_RECEIVE, module: 'production', description: 'Receive finished/semi-finished production output' },
  { code: PermissionCodes.PRODUCTION_OVERHEAD_MANAGE, module: 'production', description: 'Create/allocate production overhead pools' },
  { code: PermissionCodes.PRODUCTION_VARIANCE_VIEW, module: 'production', description: 'Calculate/view production variances' },
  { code: PermissionCodes.PRODUCTION_ORDER_CLOSE, module: 'production', description: 'Close a production order' },

  { code: PermissionCodes.PERIOD_CLOSE_VIEW, module: 'period_close', description: 'View financial periods, close runs, and readiness' },
  { code: PermissionCodes.PERIOD_CLOSE_PREVIEW, module: 'period_close', description: 'Run a read-only Month Close preview' },
  { code: PermissionCodes.PERIOD_CLOSE_RUN, module: 'period_close', description: 'Create a financial period and start an authoritative close run' },
  { code: PermissionCodes.PERIOD_CLOSE_STEP_RUN, module: 'period_close', description: 'Retry an individual close step' },
  { code: PermissionCodes.PERIOD_CLOSE_RESOLVE_ISSUE, module: 'period_close', description: 'Mark a close issue resolved' },
  { code: PermissionCodes.PERIOD_CLOSE_WAIVE_WARNING, module: 'period_close', description: 'Waive a close issue, including an accepted-exception override on a blocking one' },
  { code: PermissionCodes.PERIOD_CLOSE_MANUAL_ADJUSTMENT, module: 'period_close', description: 'Create/post a manual accrual or deferred revenue schedule' },
  { code: PermissionCodes.PERIOD_SOFT_CLOSE, module: 'period_close', description: 'Soft-close a financial period' },
  { code: PermissionCodes.PERIOD_HARD_CLOSE, module: 'period_close', description: 'Hard-close a financial period (locks ordinary posting)' },
  { code: PermissionCodes.PERIOD_REOPEN_REQUEST, module: 'period_close', description: 'Request a controlled reopen of a closed period' },
  { code: PermissionCodes.PERIOD_REOPEN_APPROVE, module: 'period_close', description: 'Approve a period reopen request' },
  { code: PermissionCodes.PERIOD_RECLOSE, module: 'period_close', description: 'Reclose a period after a reopen correction' },
  { code: PermissionCodes.PERIOD_VIEW_RECONCILIATION, module: 'period_close', description: 'View subledger-vs-GL reconciliation results' },
  { code: PermissionCodes.PERIOD_VIEW_TAX, module: 'period_close', description: 'View tax close reconciliation results' },
  { code: PermissionCodes.PERIOD_VIEW_PAYROLL, module: 'period_close', description: 'View payroll close details from the Month Close dashboard' },
  { code: PermissionCodes.PERIOD_VIEW_CLOSE_AUDIT, module: 'period_close', description: 'View the full Month Close audit trail' },

  { code: PermissionCodes.FIN_REPORT_VIEW, module: 'fin_report', description: 'View financial reports' },
  { code: PermissionCodes.FIN_REPORT_VIEW_PRELIMINARY, module: 'fin_report', description: 'View preliminary (open-period) financial reports' },
  { code: PermissionCodes.FIN_REPORT_VIEW_FINAL, module: 'fin_report', description: 'View final/signed financial reports' },
  { code: PermissionCodes.FIN_REPORT_TRIAL_BALANCE, module: 'fin_report', description: 'Run the Trial Balance report' },
  { code: PermissionCodes.FIN_REPORT_BALANCE_SHEET, module: 'fin_report', description: 'Run the Balance Sheet report' },
  { code: PermissionCodes.FIN_REPORT_PNL, module: 'fin_report', description: 'Run the Profit & Loss report' },
  { code: PermissionCodes.FIN_REPORT_CASH_FLOW, module: 'fin_report', description: 'Run the Cash Flow Statement' },
  { code: PermissionCodes.FIN_REPORT_EQUITY, module: 'fin_report', description: 'Run the Statement of Changes in Equity' },
  { code: PermissionCodes.FIN_REPORT_DRILLDOWN, module: 'fin_report', description: 'Drill down from a report cell to its GL source' },
  { code: PermissionCodes.FIN_REPORT_SENSITIVE_DRILLDOWN, module: 'fin_report', description: 'Drill down into sensitive (e.g. payroll) detail' },
  { code: PermissionCodes.FIN_REPORT_MAPPING_VIEW, module: 'fin_report', description: 'View report frameworks, statement definitions, and account mappings' },
  { code: PermissionCodes.FIN_REPORT_MAPPING_EDIT, module: 'fin_report', description: 'Create/edit report frameworks, statement definitions, rows, and mappings' },
  { code: PermissionCodes.FIN_REPORT_MAPPING_APPROVE, module: 'fin_report', description: 'Approve/activate a framework or statement version, or approve a mapping' },
  { code: PermissionCodes.FIN_REPORT_LAYOUT_EDIT, module: 'fin_report', description: 'Edit report layouts' },
  { code: PermissionCodes.FIN_REPORT_GENERATE, module: 'fin_report', description: 'Create/recalculate/review a financial report run' },
  { code: PermissionCodes.FIN_REPORT_APPROVE, module: 'fin_report', description: 'Approve a financial report run' },
  { code: PermissionCodes.FIN_REPORT_FINALIZE, module: 'fin_report', description: 'Finalize a financial report run' },
  { code: PermissionCodes.FIN_REPORT_SIGN, module: 'fin_report', description: 'Sign a final financial report' },
  { code: PermissionCodes.FIN_REPORT_RESTATE, module: 'fin_report', description: 'Restate a financial report as a new version' },
  { code: PermissionCodes.FIN_REPORT_EXPORT, module: 'fin_report', description: 'Export a financial report' },
  { code: PermissionCodes.FIN_REPORT_GROUP_VIEW, module: 'fin_report', description: 'View multi-entity combined (unconsolidated) reporting views' },

  { code: PermissionCodes.MGMT_REPORT_VIEW, module: 'mgmt_report', description: 'View management reports' },
  { code: PermissionCodes.MGMT_DASHBOARD_VIEW, module: 'mgmt_report', description: 'View management dashboards' },
  { code: PermissionCodes.MGMT_KPI_VIEW, module: 'mgmt_report', description: 'View KPI values and governed measures' },
  { code: PermissionCodes.MGMT_PROFITABILITY_VIEW, module: 'mgmt_report', description: 'View profitability reports' },
  { code: PermissionCodes.MGMT_CUSTOMER_PROFITABILITY, module: 'mgmt_report', description: 'View customer-level profitability' },
  { code: PermissionCodes.MGMT_PRODUCT_PROFITABILITY, module: 'mgmt_report', description: 'View product-level profitability' },
  { code: PermissionCodes.MGMT_COST_CENTER_VIEW, module: 'mgmt_report', description: 'View cost center P&L' },
  { code: PermissionCodes.MGMT_PROJECT_PNL, module: 'mgmt_report', description: 'View project P&L' },
  { code: PermissionCodes.MGMT_WORKING_CAPITAL_VIEW, module: 'mgmt_report', description: 'View working capital KPIs' },
  { code: PermissionCodes.MGMT_PRODUCTION_VIEW, module: 'mgmt_report', description: 'View production efficiency KPIs' },
  { code: PermissionCodes.MGMT_WORKFORCE_COST_VIEW, module: 'mgmt_report', description: 'View aggregate workforce cost KPIs' },
  { code: PermissionCodes.MGMT_BUDGET_VIEW, module: 'mgmt_report', description: 'View budget versions and facts' },
  { code: PermissionCodes.MGMT_BUDGET_EDIT, module: 'mgmt_report', description: 'Create/edit a draft budget version' },
  { code: PermissionCodes.MGMT_BUDGET_APPROVE, module: 'mgmt_report', description: 'Approve/lock a budget version' },
  { code: PermissionCodes.MGMT_FORECAST_EDIT, module: 'mgmt_report', description: 'Create/edit/publish a forecast version' },
  { code: PermissionCodes.MGMT_SCENARIO_CREATE, module: 'mgmt_report', description: 'Create scenarios/assumptions and calculate what-if results' },
  { code: PermissionCodes.MGMT_SEMANTIC_MODEL_EDIT, module: 'mgmt_report', description: 'Edit the management semantic model, measures, and dashboards' },
  { code: PermissionCodes.MGMT_KPI_EDIT, module: 'mgmt_report', description: 'Create/edit KPI definitions and targets' },
  { code: PermissionCodes.MGMT_ALLOCATION_EDIT, module: 'mgmt_report', description: 'Create/run management allocation rules and alert rules' },
  { code: PermissionCodes.MGMT_SNAPSHOT_CREATE, module: 'mgmt_report', description: 'Generate a management reporting snapshot/board pack' },
  { code: PermissionCodes.MGMT_EXPORT, module: 'mgmt_report', description: 'Export management reports' },
  { code: PermissionCodes.MGMT_SENSITIVE_DRILLDOWN, module: 'mgmt_report', description: 'Drill down into sensitive (employee-level) workforce/payroll detail' },

  { code: PermissionCodes.AUDIT_VIEW_ENTITY_HISTORY, module: 'audit', description: 'View a master-data/business entity\'s full change history' },
  { code: PermissionCodes.AUDIT_VIEW_DOCUMENT_HISTORY, module: 'audit', description: 'View a document\'s lifecycle and lineage history' },
  { code: PermissionCodes.AUDIT_VIEW_POSTING_TRACE, module: 'audit', description: 'View a document\'s posting/unposting/reversal trace' },
  { code: PermissionCodes.AUDIT_VIEW_CONFIG_HISTORY, module: 'audit', description: 'View configuration/rule change history' },
  { code: PermissionCodes.AUDIT_VIEW_SECURITY_EVENTS, module: 'audit', description: 'View security events and user activity' },
  { code: PermissionCodes.AUDIT_VIEW_SENSITIVE_ACCESS, module: 'audit', description: 'View and record sensitive-data access events' },
  { code: PermissionCodes.AUDIT_VIEW_SENSITIVE_VALUES, module: 'audit', description: 'View raw sensitive field values in an audit diff (not just that a change occurred)' },
  { code: PermissionCodes.AUDIT_SEARCH_GLOBAL, module: 'audit', description: 'Run a global audit event search across entity types' },
  { code: PermissionCodes.AUDIT_INVESTIGATION_CREATE, module: 'audit', description: 'Open an audit investigation' },
  { code: PermissionCodes.AUDIT_INVESTIGATION_EDIT, module: 'audit', description: 'Add items to / change the status of an audit investigation' },
  { code: PermissionCodes.AUDIT_EVIDENCE_ADD, module: 'audit', description: 'Upload/replace audit evidence' },
  { code: PermissionCodes.AUDIT_EXPORT, module: 'audit', description: 'Build an audit export package' },
  { code: PermissionCodes.AUDIT_EXPORT_SENSITIVE, module: 'audit', description: 'Build an unredacted audit export package containing sensitive values' },
  { code: PermissionCodes.AUDIT_VERIFY_INTEGRITY, module: 'audit', description: 'Verify audit hash-chain integrity and create checkpoints' },
  { code: PermissionCodes.AUDIT_LEGAL_HOLD_CREATE, module: 'audit', description: 'Create a legal hold' },
  { code: PermissionCodes.AUDIT_LEGAL_HOLD_RELEASE, module: 'audit', description: 'Release a legal hold' },
  { code: PermissionCodes.AUDIT_RETENTION_MANAGE, module: 'audit', description: 'Configure audit retention policies and evaluate disposition' },
  { code: PermissionCodes.AUDIT_ADMIN, module: 'audit', description: 'Full audit administration, including recording configuration-change audit entries' },

  { code: PermissionCodes.WORKFLOW_VIEW, module: 'workflow', description: 'View workflow instances and health' },
  { code: PermissionCodes.WORKFLOW_VIEW_OWN, module: 'workflow', description: 'View own approval inbox' },
  { code: PermissionCodes.WORKFLOW_VIEW_DEPARTMENT, module: 'workflow', description: "View a department's workflow instances" },
  { code: PermissionCodes.WORKFLOW_APPROVE, module: 'workflow', description: 'Start a workflow and approve pending steps' },
  { code: PermissionCodes.WORKFLOW_REJECT, module: 'workflow', description: 'Reject a pending workflow step' },
  { code: PermissionCodes.WORKFLOW_REQUEST_CHANGE, module: 'workflow', description: 'Request a change on a pending workflow step' },
  { code: PermissionCodes.WORKFLOW_DELEGATE, module: 'workflow', description: 'Create a delegation rule for own approvals' },
  { code: PermissionCodes.WORKFLOW_ADMIN, module: 'workflow', description: 'Full workflow administration (approver rules, execution-gate checks) — never a bypass of business approval gates' },
  { code: PermissionCodes.WORKFLOW_DEFINITION_VIEW, module: 'workflow', description: 'View workflow definitions and versions' },
  { code: PermissionCodes.WORKFLOW_DEFINITION_EDIT, module: 'workflow', description: 'Create/edit workflow definitions, versions, and steps' },
  { code: PermissionCodes.WORKFLOW_DEFINITION_APPROVE, module: 'workflow', description: 'Activate a workflow version' },
  { code: PermissionCodes.WORKFLOW_RESTART, module: 'workflow', description: 'Restart a cancelled/change-requested workflow instance' },
  { code: PermissionCodes.WORKFLOW_CANCEL, module: 'workflow', description: 'Cancel a pending workflow instance' },
  { code: PermissionCodes.WORKFLOW_ESCALATE, module: 'workflow', description: 'Manually trigger workflow escalation' },
  { code: PermissionCodes.WORKFLOW_OVERRIDE_SOD, module: 'workflow', description: 'Override a segregation-of-duties conflict where policy allows, with mandatory reason' },
  { code: PermissionCodes.WORKFLOW_VIEW_AUDIT, module: 'workflow', description: 'View full workflow audit trail' },
  { code: PermissionCodes.WORKFLOW_VIEW_SENSITIVE, module: 'workflow', description: 'View sensitive workflow context (e.g. payroll/HR approval details)' },

  { code: PermissionCodes.DOC_CHAIN_VIEW, module: 'doc_chain', description: 'View document chain relationships, provenance, and consumption' },
  { code: PermissionCodes.DOC_CHAIN_TYPE_MANAGE, module: 'doc_chain', description: 'Manage document type definitions' },
  { code: PermissionCodes.DOC_CHAIN_TRANSFORMATION_MANAGE, module: 'doc_chain', description: 'Author/edit document transformation definitions and draft versions' },
  { code: PermissionCodes.DOC_CHAIN_TRANSFORMATION_APPROVE, module: 'doc_chain', description: 'Activate a document transformation version' },
  { code: PermissionCodes.CREATE_BASED_ON_PROPOSE, module: 'doc_chain', description: 'Generate a create-based-on document creation proposal from a source document' },
  { code: PermissionCodes.CREATE_BASED_ON_ACCEPT, module: 'doc_chain', description: 'Accept a document creation proposal and materialize a target document' },
  { code: PermissionCodes.DOC_CHAIN_CLAIM_MANAGE, module: 'doc_chain', description: 'Create/release source creation claims' },
  { code: PermissionCodes.DOC_CHAIN_RELATIONSHIP_VIEW, module: 'doc_chain', description: 'View document/line relationships and the dependency graph' },
  { code: PermissionCodes.DOC_CHAIN_LINEAGE_VIEW, module: 'doc_chain', description: 'View forward/backward document lineage' },
  { code: PermissionCodes.DOC_CHAIN_IMPACT_VIEW, module: 'doc_chain', description: 'Run transitive downstream impact analysis before editing/unposting/cancelling a source document' },
  { code: PermissionCodes.DOC_CHAIN_IMPACT_OVERRIDE, module: 'doc_chain', description: 'Override a blocking downstream-impact result, with mandatory reason' },
  { code: PermissionCodes.DOC_CHAIN_EXCEPTION_VIEW, module: 'doc_chain', description: 'View transformation exceptions' },
  { code: PermissionCodes.DOC_CHAIN_EXCEPTION_RESOLVE, module: 'doc_chain', description: 'Resolve a transformation exception' },

  { code: PermissionCodes.INTEGRATION_VIEW, module: 'integration', description: 'View integration platform data' },
  { code: PermissionCodes.INTEGRATION_ENDPOINT_VIEW, module: 'integration', description: 'View integration endpoints' },
  { code: PermissionCodes.INTEGRATION_ENDPOINT_EDIT, module: 'integration', description: 'Create/edit integration endpoints' },
  { code: PermissionCodes.INTEGRATION_CONNECTOR_VIEW, module: 'integration', description: 'View connectors and connector versions' },
  { code: PermissionCodes.INTEGRATION_CONTRACT_VIEW, module: 'integration', description: 'View integration contracts and versions' },
  { code: PermissionCodes.INTEGRATION_CONTRACT_EDIT, module: 'integration', description: 'Create/edit integration contracts and versions' },
  { code: PermissionCodes.INTEGRATION_MAPPING_VIEW, module: 'integration', description: 'View mapping profiles and versions' },
  { code: PermissionCodes.INTEGRATION_MAPPING_EDIT, module: 'integration', description: 'Author mapping profiles/versions' },
  { code: PermissionCodes.INTEGRATION_MAPPING_APPROVE, module: 'integration', description: 'Activate a mapping version' },
  { code: PermissionCodes.INTEGRATION_IMPORT_RUN, module: 'integration', description: 'Run an import preview/dry-run' },
  { code: PermissionCodes.INTEGRATION_IMPORT_COMMIT, module: 'integration', description: 'Commit a staged import batch' },
  { code: PermissionCodes.INTEGRATION_EXPORT_RUN, module: 'integration', description: 'Run an export job' },
  { code: PermissionCodes.INTEGRATION_REPLAY, module: 'integration', description: 'Replay a failed integration message' },
  { code: PermissionCodes.INTEGRATION_DEADLETTER_RESOLVE, module: 'integration', description: 'Resolve/ignore a dead-lettered message' },
  { code: PermissionCodes.INTEGRATION_MANUAL_MATCH, module: 'integration', description: 'Manually link an external entity reference' },
  { code: PermissionCodes.INTEGRATION_RECONCILIATION_RUN, module: 'integration', description: 'Run a reconciliation' },
  { code: PermissionCodes.INTEGRATION_CREDENTIAL_ROTATE, module: 'integration', description: 'Rotate an integration credential reference' },
  { code: PermissionCodes.INTEGRATION_VIEW_PAYLOAD, module: 'integration', description: 'View integration payload metadata (never raw secrets)' },
  { code: PermissionCodes.INTEGRATION_VIEW_SENSITIVE_PAYLOAD, module: 'integration', description: 'View unmasked sensitive payload content where policy allows' },
  { code: PermissionCodes.INTEGRATION_ADMIN, module: 'integration', description: 'Full integration platform administration' },

  { code: PermissionCodes.AI_USE, module: 'ai', description: 'Use the general ERP AI assistant (read-only Q&A)' },
  { code: PermissionCodes.AI_FINANCIAL_ANALYSIS, module: 'ai', description: 'Use AI financial-analysis capabilities' },
  { code: PermissionCodes.AI_MANAGEMENT_INSIGHTS, module: 'ai', description: 'Use AI management/KPI insight capabilities' },
  { code: PermissionCodes.AI_DOCUMENT_ASSIST, module: 'ai', description: 'Use AI document classification/summary assistance' },
  { code: PermissionCodes.AI_MATCHING, module: 'ai', description: 'Use AI matching/candidate-resolution capabilities' },
  { code: PermissionCodes.AI_AUDIT_ASSIST, module: 'ai', description: 'Use AI audit-investigation summarization' },
  { code: PermissionCodes.AI_PAYROLL_EXPLAIN, module: 'ai', description: 'Use AI payroll explanation (still gated by underlying payroll permissions)' },
  { code: PermissionCodes.AI_SENSITIVE_CONTEXT, module: 'ai', description: 'Allow AI retrieval to include sensitive-domain context where the user also holds the underlying business permission' },
  { code: PermissionCodes.AI_ACTION_PROPOSE, module: 'ai', description: 'Allow AI to generate action proposals' },
  { code: PermissionCodes.AI_ACTION_ACCEPT, module: 'ai', description: 'Accept an AI action proposal (still subject to normal business SoD/workflow)' },
  { code: PermissionCodes.AI_HIGH_RISK_PROPOSE, module: 'ai', description: 'Allow AI to generate HIGH/CRITICAL risk action proposals' },
  { code: PermissionCodes.AI_CONFIG_VIEW, module: 'ai', description: 'View AI platform configuration' },
  { code: PermissionCodes.AI_CONFIG_EDIT, module: 'ai', description: 'Edit AI providers/capabilities/assistants/retrieval policy' },
  { code: PermissionCodes.AI_MODEL_APPROVE, module: 'ai', description: 'Activate a model version for production use' },
  { code: PermissionCodes.AI_PROMPT_APPROVE, module: 'ai', description: 'Activate a prompt version for production use' },
  { code: PermissionCodes.AI_TOOL_APPROVE, module: 'ai', description: 'Approve a new/changed AI tool definition' },
  { code: PermissionCodes.AI_EVAL_RUN, module: 'ai', description: 'Run an AI evaluation' },
  { code: PermissionCodes.AI_EVAL_APPROVE, module: 'ai', description: 'Approve an evaluation run as a release gate' },
  { code: PermissionCodes.AI_USAGE_VIEW, module: 'ai', description: 'View AI usage/cost metrics' },
  { code: PermissionCodes.AI_AUDIT_VIEW, module: 'ai', description: 'View full AI interaction/proposal audit trail' },
];
